"""Canonical IPC contract models, schema, and validation for the Rino runtime."""

from rino_runtime.contracts.message_families import (
    DEFAULT_MAXIMUM_FRAME_BYTES,
    EVENT_FAMILIES,
    PROTOCOL_VERSION,
    REQUEST_FAMILIES,
    RUNTIME_EVENT_FAMILIES,
    RUNTIME_REQUEST_FAMILIES,
    SYSTEM_EVENT_FAMILIES,
    SYSTEM_REQUEST_FAMILIES,
    RequestFamily,
)
from rino_runtime.contracts.models import (
    IPC_MESSAGE_ADAPTER,
    ErrorResponseEnvelopeV1,
    EventEnvelopeV1,
    IpcMessageV1,
    ProtocolErrorV1,
    RequestEnvelopeV1,
    ResponseEnvelopeV1,
    SuccessResponseEnvelopeV1,
    dump_model,
    parse_message,
    serialize_message,
)
from rino_runtime.contracts.validation import (
    describe_message_errors,
    describe_project_document_errors,
    describe_registry_snapshot_errors,
    is_valid_graph_definition,
    is_valid_message,
    is_valid_payload,
    is_valid_project_document,
    is_valid_registry_definition,
    is_valid_registry_snapshot,
)

__all__ = [
    "DEFAULT_MAXIMUM_FRAME_BYTES",
    "EVENT_FAMILIES",
    "IPC_MESSAGE_ADAPTER",
    "PROTOCOL_VERSION",
    "REQUEST_FAMILIES",
    "RUNTIME_EVENT_FAMILIES",
    "RUNTIME_REQUEST_FAMILIES",
    "SYSTEM_EVENT_FAMILIES",
    "SYSTEM_REQUEST_FAMILIES",
    "ErrorResponseEnvelopeV1",
    "EventEnvelopeV1",
    "IpcMessageV1",
    "ProtocolErrorV1",
    "RequestEnvelopeV1",
    "RequestFamily",
    "ResponseEnvelopeV1",
    "SuccessResponseEnvelopeV1",
    "describe_message_errors",
    "describe_project_document_errors",
    "describe_registry_snapshot_errors",
    "dump_model",
    "is_valid_graph_definition",
    "is_valid_message",
    "is_valid_payload",
    "is_valid_project_document",
    "is_valid_registry_definition",
    "is_valid_registry_snapshot",
    "parse_message",
    "serialize_message",
]
