from maa.job import Job, JobWithResult
from numpy import uint8
from numpy.typing import NDArray

class ControllerEventSink:
    def on_raw_notification(
        self,
        controller: Controller,
        msg: str,
        details: dict[str, object],
    ) -> None: ...

class Controller:
    def add_sink(self, sink: ControllerEventSink) -> int | None: ...
    def remove_sink(self, sink_id: int) -> None: ...
    def post_connection(self) -> Job: ...
    def post_screencap(self) -> JobWithResult: ...
    def post_click(
        self,
        x: int,
        y: int,
        contact: int = 0,
        pressure: int = 1,
    ) -> Job: ...
    def set_screenshot_use_raw_size(self, enable: bool) -> bool: ...

class CustomController(Controller):
    def __init__(self) -> None: ...
    def connect(self) -> bool: ...
    def connected(self) -> bool: ...
    def request_uuid(self) -> str: ...
    def get_features(self) -> int: ...
    def start_app(self, intent: str) -> bool: ...
    def stop_app(self, intent: str) -> bool: ...
    def screencap(self) -> NDArray[uint8]: ...
    def click(self, x: int, y: int) -> bool: ...
    def swipe(
        self,
        x1: int,
        y1: int,
        x2: int,
        y2: int,
        duration: int,
    ) -> bool: ...
    def touch_down(
        self,
        contact: int,
        x: int,
        y: int,
        pressure: int,
    ) -> bool: ...
    def touch_move(
        self,
        contact: int,
        x: int,
        y: int,
        pressure: int,
    ) -> bool: ...
    def touch_up(self, contact: int) -> bool: ...
    def click_key(self, keycode: int) -> bool: ...
    def input_text(self, text: str) -> bool: ...
    def key_down(self, keycode: int) -> bool: ...
    def key_up(self, keycode: int) -> bool: ...
