import {
  Ban,
  Braces,
  Bug,
  Circle,
  CircleAlert,
  CircleCheck,
  CirclePause,
  CircleQuestionMark,
  CircleX,
  Check,
  ChevronDown,
  ChevronUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  Clock3,
  Command,
  Crosshair,
  FilePlus,
  FileText,
  FolderOpen,
  Gamepad2,
  GripVertical,
  Hand,
  PlugZap,
  GitBranch,
  GitCompareArrows,
  Image,
  Images,
  Pencil,
  Keyboard,
  LayoutGrid,
  List,
  ListTree,
  ListChecks,
  LoaderCircle,
  MousePointer2,
  Maximize2,
  MoveHorizontal,
  Palette,
  PanelBottom,
  PanelLeft,
  PanelRight,
  Pause,
  PackageOpen,
  Play,
  Plus,
  RotateCcw,
  RefreshCw,
  Save,
  SaveAll,
  ScanSearch,
  ScanText,
  Search,
  Settings,
  Smartphone,
  SlidersHorizontal,
  Square,
  TerminalSquare,
  TriangleAlert,
  Trash2,
  Unplug,
  Variable,
  X,
  Workflow,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const productIcons = {
  "action.newProject": FilePlus,
  "action.save": Save,
  "action.saveAs": SaveAll,
  "action.open": FolderOpen,
  "action.search": Search,
  "action.commandSearch": Command,
  "action.settings": Settings,
  "action.publish": PackageOpen,
  "action.help": CircleQuestionMark,
  "action.keyboardReference": Keyboard,
  "action.debugPanel": Bug,
  "action.inspectorPanel": PanelRight,
  "action.close": X,
  "action.drag": GripVertical,
  "action.collapseLeft": ChevronsLeft,
  "action.expandLeft": ChevronsRight,
  "action.collapseRight": ChevronsRight,
  "action.expandRight": ChevronsLeft,
  "action.collapseDown": ChevronsDown,
  "action.expandUp": ChevronsUp,
  "action.expandPreview": Maximize2,
  "action.gridView": LayoutGrid,
  "action.listView": List,
  "action.check": Check,
  "action.add": Plus,
  "action.manageTasks": ListTree,
  "action.editTask": Pencil,
  "action.deleteTask": Trash2,
  "action.chevronDown": ChevronDown,
  "action.chevronUp": ChevronUp,
  "panel.palette": PanelLeft,
  "panel.canvas": Workflow,
  "panel.device": Gamepad2,
  "device.connect": PlugZap,
  "device.disconnect": Unplug,
  "device.refresh": RefreshCw,
  "panel.inspector": SlidersHorizontal,
  "panel.debug": PanelBottom,
  "panel.problems": TriangleAlert,
  "panel.logs": TerminalSquare,
  "panel.values": Braces,
  "panel.ocr": ScanText,
  "panel.execution": ListChecks,
  "panel.breakpoints": CirclePause,
  "run.start": Play,
  "run.stop": Square,
  "run.pause": Pause,
  "run.restart": RotateCcw,
  "category.flow": Workflow,
  "category.recognition": ScanSearch,
  "category.action": MousePointer2,
  "category.logic": GitBranch,
  "category.data": Braces,
  "category.utility": Wrench,
  "node.ocr": ScanText,
  "node.imageRecognition": Images,
  "node.click": MousePointer2,
  "node.touchAction": Hand,
  "node.launchAndroidApp": Smartphone,
  "node.pressAndroidKey": Keyboard,
  "node.swipe": MoveHorizontal,
  "node.delay": Clock3,
  "node.log": FileText,
  "node.compare": GitCompareArrows,
  "node.branch": GitBranch,
  "node.coordinate": Crosshair,
  "node.variable": Variable,
  "node.collection": ListTree,
  "recognition.ocr": ScanText,
  "recognition.template": Image,
  "recognition.feature": ScanSearch,
  "recognition.color": Palette,
  "runtime.idle": Circle,
  "runtime.running": LoaderCircle,
  "runtime.succeeded": CircleCheck,
  "runtime.failed": CircleX,
  "runtime.paused": CirclePause,
  "runtime.disabled": Ban,
  "runtime.warning": CircleAlert,
} as const satisfies Record<string, LucideIcon>;

export type ProductIconKey = keyof typeof productIcons;

/** Resolves an icon key supplied by data, such as a node definition.
 *
 * An unrecognized key falls back rather than failing: a registry from a newer runtime may
 * name an icon this build does not ship, and that must not stop the node from rendering.
 */
export function resolveProductIcon(
  iconKey: string,
  fallback: ProductIconKey,
): ProductIconKey {
  return Object.hasOwn(productIcons, iconKey)
    ? (iconKey as ProductIconKey)
    : fallback;
}
