"""Bounded errors for the MaaFramework integration boundary."""

from __future__ import annotations

from enum import StrEnum


class MaaBackendErrorCode(StrEnum):
    BINDING_UNAVAILABLE = "MAA_BINDING_UNAVAILABLE"
    VERSION_MISMATCH = "MAA_VERSION_MISMATCH"
    INITIALIZATION_FAILED = "MAA_INITIALIZATION_FAILED"
    NOT_INITIALIZED = "MAA_NOT_INITIALIZED"
    DEVICE_DISCOVERY_FAILED = "MAA_DEVICE_DISCOVERY_FAILED"
    DEVICE_NOT_FOUND = "MAA_DEVICE_NOT_FOUND"
    DEVICE_NOT_CONNECTED = "MAA_DEVICE_NOT_CONNECTED"
    DEVICE_CONNECTION_FAILED = "MAA_DEVICE_CONNECTION_FAILED"
    DEVICE_CONNECTION_LOST = "MAA_DEVICE_CONNECTION_LOST"
    DEVICE_DEACTIVATION_FAILED = "MAA_DEVICE_DEACTIVATION_FAILED"
    SCREEN_CAPTURE_FAILED = "MAA_SCREEN_CAPTURE_FAILED"
    SCREEN_CAPTURE_INVALID = "MAA_SCREEN_CAPTURE_INVALID"
    SCREEN_CAPTURE_TOO_LARGE = "MAA_SCREEN_CAPTURE_TOO_LARGE"
    OCR_UNAVAILABLE = "MAA_OCR_UNAVAILABLE"
    OCR_MODEL_INVALID = "MAA_OCR_MODEL_INVALID"
    OCR_MODEL_LOAD_FAILED = "MAA_OCR_MODEL_LOAD_FAILED"
    OCR_SESSION_FAILED = "MAA_OCR_SESSION_FAILED"
    OCR_RECOGNITION_FAILED = "MAA_OCR_RECOGNITION_FAILED"
    OCR_RESULT_INVALID = "MAA_OCR_RESULT_INVALID"
    RECOGNITION_UNAVAILABLE = "MAA_RECOGNITION_UNAVAILABLE"
    RECOGNITION_SESSION_FAILED = "MAA_RECOGNITION_SESSION_FAILED"
    RECOGNITION_FAILED = "MAA_RECOGNITION_FAILED"
    RECOGNITION_RESULT_INVALID = "MAA_RECOGNITION_RESULT_INVALID"
    ACTION_REJECTED = "MAA_ACTION_REJECTED"
    ACTION_OUTCOME_UNKNOWN = "MAA_ACTION_OUTCOME_UNKNOWN"
    PREVIEW_UNAVAILABLE = "MAA_PREVIEW_UNAVAILABLE"
    PREVIEW_ENCODE_FAILED = "MAA_PREVIEW_ENCODE_FAILED"
    PREVIEW_TOO_LARGE = "MAA_PREVIEW_TOO_LARGE"
    PREVIEW_STORAGE_FAILED = "MAA_PREVIEW_STORAGE_FAILED"
    CAPTURE_ARTIFACT_UNAVAILABLE = "MAA_CAPTURE_ARTIFACT_UNAVAILABLE"
    CAPTURE_ARTIFACT_INVALID = "MAA_CAPTURE_ARTIFACT_INVALID"
    CAPTURE_ARTIFACT_ENCODE_FAILED = "MAA_CAPTURE_ARTIFACT_ENCODE_FAILED"
    CAPTURE_ARTIFACT_TOO_LARGE = "MAA_CAPTURE_ARTIFACT_TOO_LARGE"
    CAPTURE_ARTIFACT_STORAGE_FAILED = "MAA_CAPTURE_ARTIFACT_STORAGE_FAILED"
    SERVICE_CLOSED = "MAA_DEVICE_SERVICE_CLOSED"
    OPERATION_TIMEOUT = "MAA_DEVICE_OPERATION_TIMEOUT"


class MaaBackendError(RuntimeError):
    """An integration failure that never embeds device identifiers or local paths."""

    def __init__(
        self,
        code: MaaBackendErrorCode,
        technical_detail: str,
        *,
        retryable: bool,
    ) -> None:
        super().__init__(code.value)
        self.code = code
        self.technical_detail = technical_detail
        self.retryable = retryable
