"""Reviewed node definitions, executors, and immutable registries."""

from rino_runtime.execution_control import CancellationProbe, NeverCancelled
from rino_runtime.nodes.builtins import (
    FakeActionRecord,
    FakeActionRecorder,
    InMemoryFakeActionRecorder,
    build_capture_and_ocr_backend_registry,
    build_capture_backend_registry,
    build_maa_backend_registry,
    build_mvp_production_registry,
    build_phase_4_fake_backend_registry,
    build_phase_4_production_registry,
    build_phase_4_test_registry,
)
from rino_runtime.nodes.execution import (
    NodeActivationTiming,
    NodeExecutionContext,
    NodeExecutionFailure,
    NodeExecutionFailureCode,
    NodeExecutionResult,
    NodeExecutor,
    RuntimeImageReference,
    RuntimeLogEntry,
    RuntimeLogLevel,
    RuntimeOcrCandidate,
    RuntimeOcrResult,
    RuntimePoint,
    RuntimeRect,
    RuntimeValue,
    SuccessorDispatchMode,
    runtime_value_matches,
)
from rino_runtime.nodes.registry import (
    MVP_BACKEND_CAPABILITY_ALLOWLIST,
    MVP_MAA_NODE_TYPE_KEYS,
    MVP_PRODUCTION_NODE_TYPE_KEYS,
    PHASE_4_PRODUCTION_NODE_TYPE_KEYS,
    TEST_NODE_TYPE_KEYS,
    NodeRegistration,
    NodeRegistry,
    NodeRegistryBuilder,
    RegistryAvailability,
)

__all__ = [
    "MVP_BACKEND_CAPABILITY_ALLOWLIST",
    "MVP_MAA_NODE_TYPE_KEYS",
    "MVP_PRODUCTION_NODE_TYPE_KEYS",
    "PHASE_4_PRODUCTION_NODE_TYPE_KEYS",
    "TEST_NODE_TYPE_KEYS",
    "CancellationProbe",
    "FakeActionRecord",
    "FakeActionRecorder",
    "InMemoryFakeActionRecorder",
    "NeverCancelled",
    "NodeActivationTiming",
    "NodeExecutionContext",
    "NodeExecutionFailure",
    "NodeExecutionFailureCode",
    "NodeExecutionResult",
    "NodeExecutor",
    "NodeRegistration",
    "NodeRegistry",
    "NodeRegistryBuilder",
    "RegistryAvailability",
    "RuntimeImageReference",
    "RuntimeLogEntry",
    "RuntimeLogLevel",
    "RuntimeOcrCandidate",
    "RuntimeOcrResult",
    "RuntimePoint",
    "RuntimeRect",
    "RuntimeValue",
    "SuccessorDispatchMode",
    "build_capture_and_ocr_backend_registry",
    "build_capture_backend_registry",
    "build_maa_backend_registry",
    "build_mvp_production_registry",
    "build_phase_4_fake_backend_registry",
    "build_phase_4_production_registry",
    "build_phase_4_test_registry",
    "runtime_value_matches",
]
