export type {
  RinoIpcMessageV1,
  RequestEnvelopeV1,
  SuccessResponseEnvelopeV1,
  ErrorResponseEnvelopeV1,
  EventEnvelopeV1,
  ProtocolErrorV1,
  ErrorCauseEntryV1,
  HandshakeRequestPayloadV1,
  HandshakeResultV1,
  HealthResultV1,
  ShutdownResultV1,
  SystemReadyEventPayloadV1,
  SystemHealthChangedEventPayloadV1,
  SystemProtocolErrorEventPayloadV1,
  AutomationOperationStateChangedEventPayloadV1,
  AutomationCallbackDiagnosticEventPayloadV1,
  PersistentVariableValueV1,
  PersistentBoolVariableV1,
  PersistentNumberVariableV1,
  PersistentStringVariableV1,
  PersistentPointValueV1,
  PersistentPointVariableV1,
  PersistentRectValueV1,
  PersistentRectVariableV1,
  MaaRuntimeStateV1,
  DeviceKeyV1,
  DeviceStateV1,
  DeviceDescriptorV1,
  DeviceListResultV1,
  DeviceConnectRequestPayloadV1,
  DeviceConnectResultV1,
  DeviceDisconnectRequestPayloadV1,
  DeviceDisconnectResultV1,
  DeviceInteractionV1,
  DeviceInteractionPointV1,
  DeviceClickInteractionV1,
  DeviceLongPressInteractionV1,
  DeviceSwipeInteractionV1,
  DeviceInteractRequestPayloadV1,
  DeviceInteractResultV1,
  DeviceStateChangedEventPayloadV1,
  CaptureTokenV1,
  CaptureRegionV1,
  CaptureArtifactDescriptorV1,
  CapturePrepareRequestPayloadV1,
  CapturePrepareResultV1,
  CaptureReleaseRequestPayloadV1,
  CaptureReleaseResultV1,
  PreviewTokenV1,
  PreviewArtifactDescriptorV1,
  PreviewCaptureRequestPayloadV1,
  PreviewCaptureResultV1,
  PreviewReleaseRequestPayloadV1,
  PreviewReleaseResultV1,
  ProtocolVersionRangeV1,
  RegistryGetResultV1,
  GraphValidateRequestPayloadV1,
  GraphValidateResultV1,
  RunStartRequestPayloadV1,
  RunStartResultV1,
  RunCancelRequestPayloadV1,
  RunCancelResultV1,
  RunStateChangedEventPayloadV1,
  NodeStateChangedEventPayloadV1,
  EdgeTraversedEventPayloadV1,
  RuntimeLogCreatedEventPayloadV1,
  RuntimeTerminalErrorV1,
  RuntimeValueSummaryV1,
} from "./generated/rino-ipc-v1.types";
export { rinoIpcV1Schema } from "./generated/rino-ipc-v1.schema";

export type {
  RinoProjectDocumentV1,
  ProjectManifestV1,
  ProjectGraphFileV1,
  ProjectMetadataV1,
  GraphDocumentV1,
  GraphFileNameV1,
  GraphV1,
  GraphKindV1,
  FunctionParameterV1,
  FunctionSignatureV1,
  GraphCommentV1,
  GraphEditorMetadataV1,
  RepeatHintV1,
  WorkflowGroupKindV1,
  WorkflowGroupMemberV1,
  WorkflowGroupPortV1,
  WorkflowGroupV1,
  NodeV1,
  NodeTypeKeyV1,
  EdgeV1,
  EdgeKindV1,
  EditorPositionV1,
  PortIdV1,
  CapabilityKeyV1,
  ImageAssetV1,
  AssetSourceKindV1,
  CoordinateSpaceV1,
} from "./generated/rino-graph-v1.types";
export { rinoGraphV1Schema } from "./generated/rino-graph-v1.schema";

export type {
  RinoNodeRegistrySnapshotV1,
  NodeDefinitionV1,
  NodeCategoryV1,
  RuntimeKindV1,
  SideEffectV1,
  PortDefinitionV1,
  PortDirectionV1,
  PortKindV1,
  TypeDescriptorV1,
  PrimitiveTypeV1,
  PrimitiveTypeKindV1,
  CollectionTypeV1,
  OptionalTypeV1,
  DeprecationV1,
  IconKeyV1,
  LocalizationKeyV1,
  WorkflowTemplateV1,
  TemplateNodeV1,
  TemplateEdgeV1,
  TemplateWorkflowGroupMemberV1,
  TemplateWorkflowGroupPortV1,
  TemplateWorkflowGroupV1,
} from "./generated/rino-registry-v1.types";
export { rinoRegistryV1Schema } from "./generated/rino-registry-v1.schema";

export type {
  RinoGraphDiagnosticReportV1,
  GraphDiagnosticV1,
  GraphDiagnosticCodeV1,
  DiagnosticSeverityV1,
  DiagnosticLocationV1,
  DocumentLocationV1,
  GraphLocationV1,
  NodeLocationV1,
  PortLocationV1,
  EdgeLocationV1,
  AssetLocationV1,
} from "./generated/rino-diagnostics-v1.types";
export { rinoDiagnosticsV1Schema } from "./generated/rino-diagnostics-v1.schema";

export {
  DEFAULT_MAXIMUM_FRAME_BYTES,
  PROTOCOL_VERSION,
  eventFamilies,
  isEventType,
  isRequestType,
  isSystemEventType,
  isSystemRequestType,
  requestFamilies,
  runtimeEventFamilies,
  runtimeRequestFamilies,
  systemEventFamilies,
  systemRequestFamilies,
} from "./message-families";
export type {
  PayloadDefinitionName,
  EventType,
  RequestType,
  RuntimeEventType,
  RuntimeRequestType,
  SystemEventType,
  SystemRequestFamily,
  SystemRequestType,
} from "./message-families";

export {
  describeGraphDocumentErrors,
  describeMessageErrors,
  describeProjectDocumentErrors,
  describeProjectManifestErrors,
  describeRegistrySnapshotErrors,
  isValidGraphDefinition,
  isValidGraphDocument,
  isValidMessage,
  isValidPayload,
  isValidProjectDocument,
  isValidProjectManifest,
  isValidDiagnosticReport,
  isValidRegistryDefinition,
  isValidRegistrySnapshot,
} from "./validation";
