import type { CatalogShape } from "./catalog-shape";

export const zhCNTranslation = {
  app: {
    name: "Rino",
    title: "Rino",
  },
  common: {
    actions: {
      cancel: "取消",
      close: "关闭",
      confirm: "确认",
      open: "打开",
      save: "保存",
      search: "搜索",
      settings: "设置",
      collapse: "折叠",
      expand: "展开",
      run: "运行",
      stop: "停止",
    },
  },
  shell: {
    project: {
      noProject: "未打开项目",
      noProjectDescription: "打开或创建项目后，图和素材会显示在这里。",
    },
    device: {
      disconnected: "未连接设备",
      disconnectedShort: "设备未连接",
      disconnectedDescription: "连接 Android 设备或模拟器后可查看实时画面。",
      previewLabel: "设备画面",
      resolution: "分辨率",
      scaleFactor: "界面缩放",
      capture: "截取画面",
      captureDescription: "从当前设备获取一张新的预览画面。",
      pause: "暂停预览",
      connect: "连接设备",
      disconnect: "断开设备",
      selectorLabel: "设备",
      noDevices: "未发现设备",
      backendUnavailable: "设备后端未配置",
      backendUnavailableDescription:
        "当前运行时没有可用的本地 ADB 后端，无法发现或连接 Android 设备。",
      refreshDevices: "刷新设备列表",
      readyToCapture: "设备已连接",
      readyToCaptureDescription: "点击刷新按钮获取当前设备画面。",
      previewError: "无法获取设备画面",
      previewErrorDescription: "检查设备连接后重试。",
      phase: {
        loadingDevices: "正在查找设备",
        connecting: "正在连接设备",
        capturing: "正在获取画面",
        controlling: "正在执行设备操作",
      },
      previewRefresh: {
        pause: "暂停预览",
        resume: "恢复预览",
        pausedLabel: "已暂停",
        frameRate: "刷新帧率",
        framesPerSecond: "{{count}} FPS",
        status: {
          live: "实时预览",
          paused: "预览已暂停",
          stale: "画面可能已过期",
        },
        announcements: {
          paused: "设备画面预览已暂停。",
          resumed: "已恢复设备画面实时预览。",
        },
      },
      control: {
        enable: "控制设备",
        disable: "退出控制",
        surfaceLabel: "设备直接控制区",
        failure: "设备操作未能确认，请检查连接；该操作不会自动重试。",
        announcements: {
          enabled: "已开启设备控制。单击执行点击，拖动执行滑动，按住执行长按。",
          disabled: "已退出设备控制。",
          click: "设备点击已完成。",
          longPress: "设备长按已完成。",
          swipe: "设备滑动已完成。",
          back: "已向设备发送返回操作。",
        },
      },
      expandedPreview: {
        open: "放大预览",
        close: "关闭大屏预览",
        title: "设备大屏预览",
        description:
          "在屏幕中心查看并控制当前设备画面，按 Esc 返回设备上一页。",
      },
      independentWindow: {
        open: "在独立窗口打开设备预览",
        unavailable: "仅桌面主窗口可打开独立预览",
        failure: "独立预览窗口打开失败，请重试。",
        title: "设备独立预览",
        close: "关闭设备独立预览",
        waitingTitle: "等待设备画面",
        waitingDescription: "主窗口取得设备画面后，将自动显示在这里。",
        readFailure: "无法读取当前设备画面；主窗口取得下一帧后会自动重试。",
      },
      captureWorkbench: {
        fullFrame: "截取整屏",
        region: "框选区域",
        cancelRegion: "取消框选",
        title: "确认截图素材",
        nameLabel: "素材显示名称",
        namePlaceholder: "输入素材名称",
        nameHint:
          "已生成不重复的默认名称；可直接保存，也可输入更容易辨认的名称。",
        dimensions: "图像尺寸",
        origin: "来源",
        fullFrameOrigin: "整屏截图",
        regionOrigin: "区域 (X: {{x}}, Y: {{y}})",
        regionOriginUnknown: "区域截图",
        nameValid: "名称可用",
        nameConflict: "素材名称与项目内已有素材重名",
        suggestionAction: "使用建议名称：{{suggestion}}",
        actions: {
          confirm: "保存素材",
          retrySave: "重试保存",
          discard: "放弃截图",
          close: "关闭",
          reset: "完成",
        },
        steps: {
          preparing: "正在准备截图画面…",
          storing: "正在存储二进制数据…",
          filing: "正在登记素材元数据…",
          saving: "正在写入项目文件…",
        },
        completed: "截图已成功保存到项目",
        saveFailedTitle: "写入项目文件失败",
        saveFailedDescription:
          "素材元数据已写入内存，点击重试保存重新写入磁盘。",
        filingFailedTitle: "登记素材元数据失败",
        nameErrors: {
          empty: "素材名称不能为空",
          tooLong: "素材名称不能超过 200 个字符",
          controlCharacter: "素材名称包含非法控制字符",
          pathSeparator: "素材名称不能包含斜杠",
          trailingPeriod: "素材名称末尾不能是点号",
          reservedName: "素材名称为系统保留名称",
          collision: "素材名称与项目内已有素材重名",
        },
        failures: {
          preview: {
            runtimeCapture: "无法从设备取得新的截图画面。",
            previewRead: "设备画面已取得，但桌面端无法读取预览数据。",
            previewValidation: "取得的设备画面已失效或数据不完整。",
            previewPresentation: "设备画面已读取，但无法在界面中显示。",
          },
          noOpenProject: "没有打开的项目，无法保存截图。",
          projectChanged: "项目在截图过程中已切换，本次截图未保存。",
          executionLocked: "当前图正在运行或处于锁定状态，无法保存截图。",
          stalePreview: "画面已经更改，无法基于失效画面完成截图。",
          namePreparationFailed: "生成截图名称失败。请检查当前项目数据后重试。",
          runtimePrepareFailed: "设备画面已取得，但运行时未能生成截图。",
          captureReadFailed: "截图已生成，但桌面端未能读取截图数据。",
          previewCreationFailed: "截图已读取，但无法打开命名确认界面。",
          prepareFailed: "处理截图画面失败，请重试。",
          storedMetadataMismatch: "截图数据元数据不匹配。",
          documentRejected: "素材元数据未通过项目校验。",
          saveFailed: "项目文件保存失败。",
        },
        diagnosticCode: "错误代码：{{code}}",
        regionOverlay: {
          title: "截图区域选择",
          instructions:
            "在画面上拖拽或使用键盘方向键框选截图区域。Enter 确认，Esc 取消。",
          announcements: {
            started: "已开启截图框选模式。在画面上拖拽或使用方向键框选区域。",
            cancelled: "已取消区域框选。",
            accepted: "已选定 {{w}} × {{h}} 区域，正在准备截图。",
            readyForName:
              "区域截图已准备完成，可确认自动名称或输入自定义名称。",
          },
        },
      },
      coordinatePicker: {
        selectPoint: "从画面选择坐标",
        reselectPoint: "重新选择坐标",
        selectQuickClick: "快捷点击：从画面取点",
        reselectQuickClick: "重新设置快捷点击",
        selectRectangle: "从画面框选区域",
        reselectRectangle: "重新框选区域",
        cancel: "取消选择",
        pointInstruction: "在画面上点击以确定坐标，按 Enter 提交，Esc 取消。",
        rectangleInstruction: "在画面上拖拽选择区域，按 Enter 提交，Esc 取消。",
        keyboardHint:
          "方向键移动，Shift+方向键微调/大步，Enter 确认，Esc 取消。",
        mismatchWarning:
          "画面分辨率 ({{currentWidth}} × {{currentHeight}}) 与已保存的参考分辨率 ({{refWidth}} × {{refHeight}}) 不匹配。请重新选择以解锁图执行。",
        selectedSummaryPoint: "已存坐标: X {{x}}, Y {{y}}",
        selectedSummaryRect: "已存区域: X {{x}}, Y {{y}}, {{w}} × {{h}}",
        unselectedSummaryPoint: "未选择坐标点",
        unselectedSummaryRect: "未选择矩形区域",
        requiresDevice: "需要先连接设备并获取画面才能选择坐标。",
        requiresFrame: "画面尚未就绪，暂无法选择坐标。",
        announcements: {
          pointStarted:
            "已开启坐标选择模式。在画面上点击或使用方向键确认位置。",
          rectangleStarted:
            "已开启矩形框选模式。在画面上拖拽或使用方向键框选区域。",
          cancelled: "已取消选择，项目保持不变。",
          pointCommitted: "已更新坐标点为 X {{x}}, Y {{y}}。",
          rectangleCommitted:
            "已更新矩形区域为 X {{x}}, Y {{y}}, 宽度 {{width}}, 高度 {{height}}。",
          staleFrame: "画面已更改，选择模式已取消。",
          mismatch: "画面分辨率与已保存参考分辨率不一致。",
          invalidGesture: "选择范围超出图像边界，请重新操作。",
          editLocked: "当前图无法编辑或正在运行。",
          commandRejected: "坐标命令写入失败。",
        },
        aria: {
          interactionSurface: "画面坐标编辑区",
          interactionDescription:
            "使用鼠标点击/拖拽，或使用键盘方向键定位坐标。按 Enter 或 Space 确认提交，Esc 取消。",
        },
      },
    },
    screenshotBrowser: {
      open: "打开截图素材库",
      openDescription: "浏览项目截图，并将截图拖到画布中。",
      title: "截图素材库",
      description: "将截图拖入画布，会创建已绑定该素材的图像节点。",
      searchLabel: "搜索截图",
      searchPlaceholder: "按名称搜索截图",
      emptyTitle: "暂无截图",
      emptyDescription: "在工作台截取整屏或框选区域后，截图会显示在这里。",
      noResultsTitle: "没有匹配的截图",
      noResultsDescription: "换一个名称关键词试试。",
      dragHint: "将 {{name}} 拖入画布",
      sortLabel: "截图排序方式",
      sortAddedTime: "按加入时间",
      sortName: "按名称",
      viewLabel: "截图预览样式",
      gridView: "图片预览",
      listView: "列表预览",
      previewUnavailable: "无法读取此截图预览",
    },
    toolbar: {
      regionLabel: "应用工具栏",
      runGraph: "运行图",
      stopGraph: "停止运行",
      openSettings: "打开设置",
      unavailableWithoutProject: "需要先打开项目。",
      unavailableWithoutDevice: "需要先打开项目并连接设备。",
      unavailableWithoutRun: "当前没有正在运行的图。",
      runUnavailable: "运行时尚未就绪，无法运行当前图。",
      runAlreadyActive: "已有图正在运行。",
    },
    tasks: {
      switcherLabel: "切换任务",
      noTask: "未选择任务",
      manage: "管理任务",
      taskSettings: {
        open: "打开当前任务设置",
        title: "当前任务设置",
        description:
          "这些选项直接来自当前任务画布中的选择节点，修改会写入图并支持撤销。",
        empty: "当前任务没有可在顶部编辑的常规设置。",
        locked: "任务正在运行，设置暂时不可编辑。",
        invalid: "该设置节点配置无效，请在画布中检查它的选项。",
        unmatched: "当前选择已不在选项列表中，将从未匹配分支继续。",
        settingLabel: "设置 {{name}}",
      },
      activeBadge: "当前",
      defaultBadge: "默认",
      runningBadge: "运行中",
      managementTitle: "任务管理",
      managementDescription:
        "切换、创建和整理项目内的任务。任务会按列表顺序保存。",
      lockedDescription: "任务正在运行，任务切换和管理暂时不可用。",
      listLabel: "项目任务列表",
      renameLabel: "重命名任务：{{name}}",
      duplicateTask: "复制任务：{{name}}",
      renameTask: "重命名任务：{{name}}",
      deleteTask: "删除任务：{{name}}",
      duplicate: "复制",
      rename: "重命名",
      delete: "删除",
      setDefault: "设为默认",
      deleteConfirm: "确定删除“{{name}}”？此操作可通过撤销恢复。",
      copyName: "{{name}} 副本",
      createLabel: "新建任务",
      createHint: "新任务从空画布开始，并会切换为当前任务。",
      createPlaceholder: "输入任务名称",
      create: "新建",
      onlyTaskNote: "项目至少保留一个任务；如需删除，请先创建或复制其他任务。",
      errors: {
        taskNameInvalid: "任务名称不能为空，且不能超过 200 个字符。",
        taskLimitReached: "任务数量已达到上限。",
        cannotDeleteOnlyTask: "项目至少需要保留一个任务。",
        taskMissing: "任务不存在，可能已被其他操作移除。",
        executionLocked: "任务正在运行，当前操作已被锁定。",
        noDocument: "请先打开或创建项目。",
        commandRejected: "任务修改未能写入项目，请重试。",
      },
    },
    palette: {
      regionLabel: "节点库面板区域",
      title: "节点库",
      searchPlaceholder: "搜索中文或英文节点",
      searchLabel: "搜索节点",
      emptyTitle: "节点注册表尚未加载",
      emptyDescription: "运行时连接完成后，可在此搜索并拖拽可用节点。",
      open: "打开节点库",
    },
    canvas: {
      workspaceLabel: "图形编辑工作区",
      label: "图编辑画布",
      emptyTitle: "从一个项目开始",
      emptyDescription: "打开项目后，可从节点库拖入节点并连接执行流程。",
    },
    workbench: {
      regionLabel: "设备与属性工作台区域",
      title: "工作台",
      open: "打开工作台",
      device: "设备",
      inspector: "属性",
      functions: "函数库",
      variables: "整个项目共享变量",
      float: "浮动工作台",
      dock: "工作台归位",
      drag: "拖动工作台",
      resize: "调整工作台大小",
      contextMenuLabel: "工作台布局操作",
      inspectorEmptyTitle: "未选择节点",
      inspectorEmptyDescription:
        "选择画布中的节点后，可在这里编辑参数和查看校验信息。",
    },
    debug: {
      title: "调试",
      problems: "问题",
      logs: "日志",
      values: "变量",
      ocr: "OCR",
      execution: "执行",
      breakpoints: "断点",
      empty: {
        logs: { title: "暂无日志" },
        values: { title: "暂无变量值" },
        ocr: { title: "暂无 OCR 结果" },
        execution: { title: "暂无执行记录" },
        breakpoints: { title: "暂无断点" },
      },
      emptyDescription: "打开并运行图后，相关调试信息会显示在这里。",
    },
    resize: {
      palette: "调整节点库宽度",
      workbench: "调整工作台宽度",
      debug: "调整调试面板高度",
      preview: "调整设备画面与属性面板比例",
    },
    settings: {
      title: "设置",
      description: "管理界面、性能、快捷键与本机数据。",
      navigationLabel: "设置分类",
      sections: {
        appearance: "外观",
        performance: "性能",
        shortcuts: "快捷键",
        data: "数据",
      },
      appearanceTitle: "外观",
      appearanceDescription: "调整软件的主题与界面语言。",
      shortcutsTitle: "快捷键参考",
      shortcutsDescription: "搜索命令、按键或适用范围。",
      searchShortcuts: "搜索快捷键",
      command: "命令",
      keys: "按键",
      scope: "范围",
      status: "状态",
      available: "可用",
      unavailable: "尚未接入",
      noShortcutResults: "没有匹配的快捷键。",
      resetAllShortcuts: "重置全部快捷键",
      resetSingle: "重置",
      resetToDefault: "重置为默认值",
      clickToChangeShortcut: "点击修改快捷键",
      recordingPrompt: "请按下快捷键...",
      conflictWarning: "快捷键与「{{other}}」冲突，请更换按键",
      performanceTitle: "性能",
      performanceDescription: "调整画布响应和本地预览负载。",
      resourceProfile: "CPU 与内存资源预设",
      resourceProfileDescription:
        "同步调整可见节点裁剪、滚轮响应和建议预览帧率，不改变设备操作的执行顺序。",
      performanceProfiles: {
        responsive: "高响应",
        balanced: "平衡",
        efficiency: "节能",
      },
      uiRefreshRate: "界面动画刷新率上限",
      uiRefreshRateDescription:
        "控制画布动画、指针覆盖层和运行状态呈现；实际帧率不会超过屏幕或 WebView 能提供的频率，也不改变设备预览或执行速度。",
      uiRefreshRateOptions: {
        display: "跟随屏幕",
        "60": "60 Hz",
        "120": "120 Hz",
        "180": "180 Hz",
      },
      previewRefreshRate: "设备预览帧率",
      previewRefreshRateDescription:
        "较高帧率更流畅，但会增加截图、CPU 和内存带宽占用。",
      framesPerSecond: "{{count}} FPS",
      hardwareAcceleration: "显卡加速",
      hardwareAccelerationAutomatic: "系统自动",
      hardwareAccelerationDescription:
        "桌面渲染会自动使用系统可用的 GPU 合成；无需手动分配显存。",
      dataTitle: "数据",
      dataDescription: "查看仅保存在本机的软件数据和项目命名身份。",
      installationCode: "安装随机码",
      installationCodeDescription:
        "首次使用时自动生成。新截图使用该随机码组成内部名称，以区分不同安装来源的同名素材。",
      installationCodeUnavailable: "暂不可用",
      assetNameExample: "内部名称示例：{{code}}_退出按钮_01",
      storageStatus: {
        stored: "已保存在本机",
        memoryOnly: "本次运行临时使用",
      },
      localDataTitle: "数据范围",
      interfaceData: "界面与性能偏好",
      shortcutData: "自定义快捷键",
      assetNamingData: "素材命名序号",
      assetNamingRecordCount: "{{count}} 条名称记录",
      projectData: "项目、图与截图素材",
      localOnly: "仅保存在本机",
      projectFolder: "保存在用户选择的项目目录",
      installationCodePrivacy:
        "随机码不是账号或密钥，软件不会将它联网发送；它会包含在新素材的内部名称中，并可能随项目分享。",
      persistentVariablesTitle: "永久变量数据",
      persistentVariablesDescription:
        "管理跨任务运行保存的变量值；变量定义和节点仍属于项目图。",
      persistentVariablesStoredLocally: "仅本机应用数据",
      persistentVariablesProjectCount: "已保存项目数",
      persistentVariablesValueCount: "全部永久变量值数",
      persistentVariablesCurrentCount: "当前打开项目的永久变量值数",
      persistentVariablesLocalOnlyNote:
        "这些值只存在本机应用数据，不会写入项目文件或导出包。",
      clearCurrentPersistentVariables: "清除当前项目",
      clearAllPersistentVariables: "清除全部",
      persistentVariablesConfirmCurrentTitle: "清除当前项目的永久变量值？",
      persistentVariablesConfirmAllTitle: "清除全部永久变量值？",
      persistentVariablesConfirmCurrentDescription:
        "只会删除当前打开项目已保存的永久变量值。",
      persistentVariablesConfirmAllDescription:
        "会删除本机应用数据中所有项目已保存的永久变量值。",
      persistentVariablesConfirmDetails:
        "不会删除变量定义、变量节点、项目图、截图素材、安装随机码或素材命名序号。此操作无法恢复。",
      persistentVariablesConfirmAction: "确认清除",
      persistentVariablesClearSuccessCurrent:
        "已清除当前项目保存的永久变量值。",
      persistentVariablesClearSuccessAll: "已清除全部项目保存的永久变量值。",
      persistentVariablesClearMemoryOnly:
        "本次会话内已清除，但本机存储不可写，旧值可能在下次启动恢复。",
      persistentVariablesClearFailure:
        "永久变量值未能清除。请检查本机应用数据状态后重试。",
      scopes: {
        global: "全局",
        canvas: "画布",
        runtime: "运行时",
      },
    },
    shortcuts: {
      openReference: {
        label: "打开快捷键参考",
        description: "显示可搜索的快捷键列表。",
      },
      focusPalette: { label: "搜索节点", description: "聚焦节点库搜索框。" },
      focusDevice: {
        label: "打开设备工作台",
        description: "显示设备画面区域。",
      },
      save: { label: "保存项目", description: "保存当前项目的修改。" },
      saveAs: { label: "项目另存为", description: "将当前项目保存到新位置。" },
      undo: { label: "撤销", description: "撤销上一次图编辑。" },
      redo: { label: "重做", description: "恢复上一次撤销的图编辑。" },
      copy: { label: "复制节点", description: "复制选中的节点。" },
      paste: { label: "粘贴节点", description: "在画布中粘贴节点。" },
      duplicate: { label: "复制副本", description: "复制并放置选中节点。" },
      remove: { label: "删除选择", description: "删除选中的节点或连线。" },
      addNode: { label: "快捷添加节点", description: "在画布中打开节点搜索。" },
      comment: {
        label: "创建区域备注",
        description: "为所选节点创建备注框，或在画布上拖出备注区域。",
      },
      commandPalette: {
        label: "命令搜索",
        description: "搜索全局命令和节点。",
      },
      frameSelection: {
        label: "聚焦选择",
        description: "让选中的节点适合画布视口。",
      },
      frameGraph: {
        label: "适应全部节点",
        description: "让完整图适合画布视口。",
      },
      run: { label: "运行图", description: "运行当前图。" },
      stop: { label: "停止运行", description: "取消当前运行。" },
      breakpoint: { label: "切换断点", description: "切换选中节点的断点。" },
      stepOver: {
        label: "单步跳过",
        description: "执行当前节点并在下一节点暂停。",
      },
      continueRun: { label: "继续运行", description: "从暂停位置继续执行。" },
    },
  },
  graph: {
    canvas: {
      label: "节点图",
      surfaceLabel: "节点图编辑区",
      dropInvalid: "拖放内容无效，未插入节点。",
    },
    project: {
      defaultGraphName: "主图",
    },
    function: {
      navigation: {
        label: "函数导航",
        prefix: "函数",
        back: "返回上一级",
      },
      library: {
        title: "函数库",
        count: "{{count}} 个函数",
        defaultName: "函数 {{count}}",
        create: "新建函数",
        noProject: "打开项目后可创建函数。",
        empty: "还没有函数图。",
        insertCall: "插入调用",
        insertCallFor: "插入函数 {{name}} 的调用",
        selfCallDisabled: "当前函数不能插入自身调用",
        edit: "编辑函数",
        editFor: "编辑函数 {{name}}",
        delete: "删除函数",
        deleteFor: "删除函数 {{name}}",
        deleteTitle: "删除函数“{{name}}”？",
        deleteDescription: "该函数图将被删除。此操作可撤销。",
        deleteDescriptionWithCalls:
          "该函数图及引用它的 {{count}} 个调用节点将被删除。此操作可撤销。",
        deleteConfirm: "删除函数",
        dragHint: "将 {{name}} 拖到画布以插入函数调用。",
        dragDisabled: "项目运行中或没有打开的图时，不能拖动函数。",
        errors: {
          noProject: "请先新建或打开项目。",
          operationFailed: "函数操作失败，请检查函数图内容。",
          commandRejected: "函数操作未能写入项目。",
          limit: "函数数量或参数数量已达到上限。",
          name: "函数名称无效或已重复。",
          target: "函数调用目标不存在或不是函数图。",
          self: "当前函数不能调用自身。",
          recursion: "函数调用会形成直接或间接递归。",
          depth: "函数调用深度不能超过 16 层。",
        },
      },
      signature: {
        title: "函数签名",
        description: "编辑函数名称、输入和输出参数。",
        nameLabel: "函数名称",
        namePlaceholder: "输入函数名称",
        input: "输入",
        output: "输出",
        parameterName: "{{label}} 参数名称",
        parameterType: "{{label}} 参数类型",
        removeParameter: "删除参数",
        removeParameterFor: "删除 {{label}} 参数",
        parameterCount: "{{count}} / {{maximum}}",
        noParameters: "暂无参数",
        addInput: "添加输入",
        addOutput: "添加输出",
        defaultInputName: "输入 {{count}}",
        defaultOutputName: "输出 {{count}}",
        missing: "函数签名不可用。",
        types: {
          bool: "布尔",
          number: "数值",
          string: "文本",
          point: "坐标",
          rect: "区域",
          imageRef: "画面",
        },
        errors: {
          operationFailed: "参数操作失败，请检查函数签名。",
          commandRejected: "参数修改未能写入项目。",
          limit: "每个方向最多只能有 16 个参数。",
          name: "参数名称不能为空、不能重复且不能超过 80 个字符。",
          kind: "参数类型不受支持。",
          parameterMissing: "参数不存在，可能已被其他编辑删除。",
        },
      },
    },
    variable: {
      selectLabel: "变量",
      nameLabel: "变量名称",
      persistentLabel: "跨任务运行永久保存",
      create: "新建同类型变量",
      missing: "变量不存在",
      noOptions: "暂无同类型变量",
      updateFailed: "变量修改失败，请检查名称和永久保存设置。",
      createFailed: "新建变量失败，请检查当前图。",
      library: {
        count: "{{count}} 个共享变量",
        item: "{{name}} · {{type}}",
        create: "新建变量",
        createType: "新变量类型",
        createName: "新变量名称",
        createNamePlaceholder: "留空则自动命名",
        select: "选择项目共享变量",
        selected: "当前项目共享变量",
        type: "变量类型",
        sharedDescription: "此变量定义对项目内所有任务和函数生效。",
        noProject: "请先打开或创建项目，再管理共享变量。",
        noActiveGraph: "请先打开任务或函数图，再创建或编辑变量。",
        executionLocked: "项目运行期间暂时不能编辑变量。",
        empty: "当前项目还没有共享变量。",
        typeLocked: "该变量已被任务或函数节点引用，不能更改类型。",
        deleteLocked: "该变量已被任务或函数节点引用，不能删除。",
        imagePersistentDisabled: "图像变量不能跨任务运行永久保存。",
        createFailed: "新建项目变量失败，请检查变量名称。",
        updateFailed: "项目变量修改失败，请检查名称和类型。",
        dragHint: "将 {{name}} 拖到画布以插入变量节点。",
        dragDisabled: "项目运行中或没有打开的图时，不能拖动变量。",
        delete: "删除变量",
        deleteTitle: "删除变量“{{name}}”？",
        deleteDescription: "该共享变量将从项目中删除。此操作可撤销。",
        deleteConfirm: "删除变量",
        insertGetter: "插入获取变量",
        insertSetter: "插入设置变量",
        insertMenuLabel: "选择变量节点",
        insertFailed: "无法将变量节点插入当前图。",
        types: {
          bool: "布尔",
          number: "数值",
          string: "文本",
          point: "坐标",
          rect: "区域",
          imageRef: "图像",
        },
      },
    },
    node: {
      breakpoint: "已设置断点",
      disabled: "已停用",
      runtime: {
        running: "正在执行",
        succeeded: "执行成功",
        failed: "执行失败",
      },
      unresolvedTitle: "未知节点：{{typeKey}}",
      unresolvedDescription: "当前注册表没有该节点类型，内容已原样保留。",
      inlineFieldLabel: "{{node}} 的 {{port}} 输入值",
      aliasEditHint: "双击 {{node}} 的标题添加或修改备注名称",
      aliasInputLabel: "{{node}} 的备注名称",
      aliasPlaceholder: "添加备注名称",
      longAliasLabel: "节点备注",
      moreParameters: "更多参数",
      quickPick: "从模拟器取值",
      log: {
        segmentText: "文本",
        segmentTextDescription: "把本段内容按文本值拼接到日志消息中。",
        segmentNumber: "数值",
        segmentNumberDescription: "把本段内容按数值格式拼接到日志消息中。",
        addSegment: "添加片段",
        removeSegment: "删除片段",
        appendNewline: "末尾换行",
      },
      sequence: {
        addStep: "添加步骤",
        addStepFailed: "未能添加顺序执行步骤",
        stepLimit: "最多可添加 {{count}} 个步骤",
        orderEditor: "执行顺序",
        step: "步骤 {{count}}",
        moveUp: "上移步骤 {{step}}（当前位置 {{position}}）",
        moveDown: "下移步骤 {{step}}（当前位置 {{position}}）",
      },
      dynamic: {
        addBranch: "添加并行路径",
        addInput: "添加数值输入",
        addImage: "添加图片",
        addRegion: "添加识别区域",
        addPoint: "添加点击位置",
        addFailed: "未能添加动态端口",
        removeItem: "删除第 {{item}} 项",
        removeFailed: "未能删除最后一项",
      },
    },
    port: {
      required: "必填输入",
      connected: "连线提供",
      groupBoundary: "组合节点端口",
      type: {
        execution: "执行",
        boolean: "布尔",
        number: "数值",
        string: "文本",
        image: "画面",
        point: "坐标",
        rect: "区域",
        ocrCandidate: "识别候选",
        ocrResult: "识别结果",
        collectionCompact: "列表",
        collectionFull: "{{type}}列表",
        optionalCompact: "可选",
        optionalFull: "可选{{type}}",
        unknown: "未知类型",
      },
      description: {
        ocrMatched: "识别到至少一个达到最低置信度的文字候选时为真。",
        matchMatched: "找到至少一个达到当前阈值的匹配区域时为真。",
        recognitionResult:
          "包含文字候选、置信度和所在区域，可连接到读取文本或读取数值。",
        bestText: "当前置信度最高的文字候选。",
        bestRegion: "当前最佳候选所在的画面区域。",
        regionCollection: "按识别结果顺序返回所有匹配区域。",
        metricCollection: "按匹配结果顺序返回分数、特征数或像素数。",
        normalizedText: "按数值格式规则整理后的文本，可用于日志或后续解析。",
        selectedCandidate: "已按读取第几个和阅读顺序选出候选。",
        missingCandidate: "指定序号超过候选数量时从此出口继续。",
        invalidNumber: "选中的文字存在，但无法按当前格式解析为有限数值。",
        recognitionRegion: "限制识别或匹配的画面区域；未连接时使用完整画面。",
        templateImage: "用于图像匹配的项目模板画面。",
      },
      inputLabel: "{{node}} 的输入端口 {{port}}，类型 {{type}}",
      outputLabel: "{{node}} 的输出端口 {{port}}，类型 {{type}}",
      connectionGestureHint:
        "Alt + 左键断开此端口的全部连线；Ctrl + 左键拖动到同类端口可移动全部连线。",
    },
    edge: {
      executionDescription: "执行连线",
      dataDescription: "数据连线，类型 {{type}}",
    },
    comment: {
      defaultText: "备注",
      textLabel: "区域备注内容",
      remove: "删除区域备注",
      resize: "调整区域备注大小",
    },
    connection: {
      retargetRejected: "无法移动连线：目标端口与现有连线不兼容",
      rejected: {
        nodeMissing: "无法连接：节点不存在",
        portMissing: "无法连接：端口不存在",
        portDirectionMismatch: "无法连接：必须从输出端口连到输入端口",
        portKindMismatch: "无法连接：执行端口与数据端口不能互连",
        typeIncompatible: "无法连接：端口类型不兼容",
        selfConnection: "无法连接：不能连接到节点自身",
        duplicateConnection: "无法连接：这条连线已经存在",
        wouldCreateDataCycle: "无法连接：会在纯计算节点之间形成循环",
        wouldCreateMultipleParallelOnPath:
          "无法连接：同一执行路径上不能再次经过同时执行",
      },
    },
    history: {
      moveNode: "移动节点",
      moveNodes: "移动多个节点",
      moveRepeatHint: "移动重复执行提示",
      resolveNodeOverlaps: "整理重叠节点",
      connect: "创建连线",
      reconnectEdge: "改接连线",
      disconnectPort: "断开端口连线",
      retargetPortConnections: "移动端口连线",
      insertNode: "添加节点",
      insertTemplate: "插入工作流模板",
      removeSelection: "删除所选内容",
      paste: "粘贴",
      duplicate: "创建副本",
      setProperty: "编辑参数",
      resetProperty: "恢复参数默认值",
      setInputValue: "编辑输入值",
      clearInputValue: "清除输入值",
      setAlias: "修改节点备注名",
      setVariable: "编辑变量",
      addSequenceStep: "添加顺序执行步骤",
      moveSequenceStep: "调整顺序执行步骤",
      addComment: "添加区域备注",
      editComment: "编辑区域备注",
      removeComment: "删除区域备注",
      addRepeatHint: "添加重复执行提示",
      setWorkflowGroupCollapsed: "折叠或展开组合节点",
      setRecognitionMethod: "切换图像识别方式",
      setClickMethod: "切换文字识别点击方式",
      promoteInput: "拆分输入参数",
      createFunction: "新建函数",
      insertFunctionCall: "插入函数调用",
      renameFunction: "修改函数名称",
      addFunctionParameter: "添加函数参数",
      renameFunctionParameter: "修改函数参数名称",
      changeFunctionParameterKind: "修改函数参数类型",
      removeFunctionParameter: "删除函数参数",
    },
    inspector: {
      alias: "备注名称",
      aliasHelp: "只影响画布上的显示，不会改变节点类型、端口或执行行为。",
      properties: "参数",
      inputs: "输入",
      noProperties: "该节点没有可配置参数。",
      noInputs: "该节点没有数据输入。",
      required: "必填",
      resetToDefault: "恢复默认值",
      resetToDefaultHelp: "恢复为节点定义的默认值 {{value}}。",
      drivenByConnection: "该输入由连线提供，内联值不会被使用。",
      literalNotAccepted: "该输入只能由连线提供，不接受内联值。",
      storedProperties: "已保存的参数",
      storedInputValues: "已保存的内联输入值",
      hiddenProperties:
        "节点定义中还有 {{count}} 个参数超出可显示上限，取值保持不变。",
      multipleSelectedTitle: "选择了多个节点",
      multipleSelectedDescription:
        "当前选中 {{count}} 个节点。只选择一个节点即可编辑它的参数。",
      ocr: {
        title: "文字识别概览",
        methodLabel: "识别方式",
        methodValue: "中英文常用文字",
        methodDescription: "使用当前运行时提供的安全 OCR 能力。",
        roiLabel: "识别区域",
        roiConnected: "由 ROI 连线提供",
        roiFullImage: "完整画面",
        confidenceLabel: "最低置信度",
        confidenceDescription: "低于该阈值的候选结果不会被采用。",
        confidenceUnavailable: "配置不可用",
        result: {
          title: "最近一次结果",
          idleTitle: "尚未运行",
          idleDescription: "运行这张图后，此处会显示该节点的结果摘要。",
          runningTitle: "正在识别文字",
          runningDescription: "正在处理当前画面，请稍候。",
          matchedTitle: "识别到文字",
          matchedDescription: "已显示置信度最高的候选结果。",
          noMatchTitle: "未识别到文字",
          noMatchDescription: "当前画面没有达到条件的文字候选。",
          incompleteTitle: "结果摘要不完整",
          incompleteDescription:
            "运行时没有返回完整的 OCR 摘要，请查看运行日志。",
          failedTitle: "文字识别失败",
          failedDescription: "该节点执行失败，请检查设备状态和运行日志。",
          candidateCount: "候选数量",
          bestText: "最佳文字",
          bestRect: "所在区域",
          truncated: "内容较长，已显示有界摘要。",
        },
      },
      help: {
        type: "类型：{{type}}",
        default: "默认值：{{value}}",
        range: "取值范围：{{minimum}} 到 {{maximum}}",
        minimum: "最小值：{{minimum}}",
        maximum: "最大值：{{maximum}}",
      },
      validation: {
        required: "该字段必须填写。",
        notANumber: "请输入数字。",
        notAnInteger: "请输入整数。",
        tooSmall: "不能小于 {{minimum}}。",
        tooLarge: "不能大于 {{maximum}}。",
        tooShort: "长度不能少于 {{minimum}} 个字符。",
        tooLong: "长度不能超过 {{maximum}} 个字符。",
        notAChoice: "请选择列表中的选项。",
        notEditable: "该值无法在这里编辑。",
        storedValueMismatch: "已保存的值与该字段的类型不一致，请重新设置。",
      },
      unsupported: {
        typeUnsupported: "该参数类型暂时没有对应的编辑控件，取值保持不变。",
        labelMissing: "该参数缺少名称信息，无法安全编辑，取值保持不变。",
        choicesInvalid:
          "该参数的可选值缺少名称信息，无法安全编辑，取值保持不变。",
        declarationInvalid: "该节点定义的参数声明无法解析，取值保持不变。",
      },
      numericWorkflow: {
        invalidStoredValue: "保存的值无效",
        parseNumber: {
          title: "数字格式",
          decimalSeparator: "小数分隔符：{{separator}}",
          groupingSeparator: "千位分隔符：{{separator}}",
          noGrouping: "千位分隔符：无",
          invalidSetting: "格式设置无效",
          sampleUnavailable: "示例不可用",
          allowSign: "允许正负号",
          normalizeFullWidth: "全角规范化",
          minimum: "最小值：{{value}}",
          maximum: "最大值：{{value}}",
          outcomesTitle: "解析结果",
          parsedOutcome: "解析成功",
          invalidOutcome: "无效",
          equalSeparatorsWarning: "小数分隔符与千位分隔符不能相同。",
          reversedBoundsWarning: "最小值不能大于最大值。",
          invalidConfigurationWarning:
            "部分保存的格式设置无效；请在下方属性中修正后再运行。",
        },
        numberCompare: {
          title: "数值比较",
          connected: "连线提供",
          required: "需要数值",
          resultTitle: "结果",
          unsupportedOperator: "不支持的比较符：{{operator}}",
          operatorNames: {
            greaterThan: "左值大于右值",
            greaterThanOrEqual: "左值大于或等于右值",
            lessThan: "左值小于右值",
            lessThanOrEqual: "左值小于或等于右值",
            equalTo: "左值等于右值",
            notEqualTo: "左值不等于右值",
          },
          resultLabel: "结果 (Boolean)",
          relationLabel: "大小关系 (String)",
        },
        branch: {
          title: "分支路径",
          conditionLabel: "条件来源",
          connected: "连线提供",
          required: "需要条件",
          pathTrue: "真 (true)",
          pathFalse: "假 (false)",
        },
      },
    },
    palette: {
      category: {
        common: "常用",
        flow: "流程",
        logic: "逻辑",
        values: "数值",
        text: "文本",
        vision: "视觉识别",
        device: "设备操作",
        timing: "时间",
        diagnostics: "诊断",
        templates: "工作流模板",
      },
      capability: {
        unknown:
          "需要后端能力：{{capabilities}}。运行时尚未连接，暂时无法确认是否可用。",
        unavailable: "当前后端不提供所需能力：{{capabilities}}。",
      },
      templateBadge: "模板",
      templateHelp: "插入可独立编辑的常规节点组合，支持单步撤销。",
      insertionHint: "拖拽到画布指定位置，或点击在视图中央插入。",
      noResultsTitle: "没有匹配的节点",
      noResultsDescription:
        "换一个中文或英文关键词试试，也可以直接搜索节点类型标识。",
      noProjectNotice: "尚未打开项目。新建或打开项目后即可拖入节点。",
      projectRequired: "请先新建或打开项目，然后再添加节点。",
      insertionFailed: "节点添加失败，请检查当前图和运行状态。",
    },
    contextMenu: {
      label: "画布操作菜单",
      create: "添加节点",
      duplicate: "创建副本",
      paste: "粘贴",
      remove: "删除所选内容",
      resolveOverlaps: "整理重叠节点",
    },
    quickAdd: {
      title: "快速添加节点",
      description: "输入中文或英文名称，回车即可在视图中央插入节点。",
      connectTitle: "连接到新节点",
      connectDescription:
        "默认按当前连线筛选可连接节点，也可以关闭情景匹配浏览全部节点。",
      contextMatch: "情景匹配",
      contextMatchEnabledDescription: "仅显示能与当前端口正确连接的节点。",
      contextMatchDisabledDescription:
        "显示全部节点；不兼容的节点将只创建，不会自动连线。",
      resultsLabel: "候选节点",
      noCompatibleResults: "没有可以接上这条连线的节点。",
      repeatAction: "重复执行",
      repeatActionTarget: "沿原连线返回到：{{target}}",
      repeatActionNoCandidate: "当前画布没有可返回的识别节点",
    },
    repeatHint: {
      title: "重复执行",
      description: "沿原连线返回并再次执行识别",
      remove: "移除重复执行提示",
    },
    diagnostics: {
      graphDuplicateGraphId: "图标识重复",
      graphDuplicateNodeId: "节点标识重复",
      graphDuplicateEdgeId: "连线标识重复",
      graphEntryGraphMissing: "项目指向的入口图不存在",
      graphEntryKindInvalid: "项目指定的入口图必须是入口图",
      graphNonEntryKindInvalid: "非入口图必须是函数图",
      graphEntryNodeMissing: "图中缺少开始节点",
      graphMultipleEntryNodes: "图中存在多个开始节点",
      graphPureDataCycle: "纯计算节点之间形成了循环依赖",
      graphMultipleParallelOnPath: "同一执行路径上不能再次经过同时执行节点",
      graphDuplicateVariableId: "变量标识重复",
      graphDuplicateVariableName: "变量名称在规范化后重复",
      graphVariablePersistenceUnsupported: "图像变量暂不支持跨任务永久保存",
      functionDuplicateParameterId: "函数参数标识必须唯一",
      functionDuplicatePortId: "函数端口标识必须唯一",
      functionDuplicateParameterName: "函数参数名称在输入或输出中必须唯一",
      functionParallelForbidden: "函数图不能包含同时执行节点",
      functionParameterPortReserved: "函数参数端口标识不能使用 run 或 next",
      functionEntryNodeMissing: "函数图缺少函数输入节点",
      functionMultipleEntryNodes: "函数图包含多个函数输入节点",
      functionReturnNodeMissing: "函数图缺少返回节点",
      functionNodeOutsideFunction: "函数输入和返回节点只能位于函数图中",
      functionCallTargetMissing: "函数调用未指定现有函数图",
      functionCallTargetNotFunction: "函数调用目标不是函数图",
      functionRecursionForbidden: "函数图不能直接或间接调用自身",
      functionCallDepthExceeded: "函数调用深度不能超过 16 层函数帧",
      functionPersistentVariableForbidden: "函数内变量不能跨任务永久保存",
      documentDuplicateAssetId: "素材标识重复",
      documentDuplicateAssetName: "素材名称在规范化后重复",
      nodeTypeUnknown: "运行时没有提供该节点类型",
      nodeTypeVersionUnsupported:
        "节点由更新版本的定义保存，当前运行时无法解析",
      nodeTypeDeprecated: "该节点类型已废弃",
      nodeVariableUnknown: "变量节点引用的变量不存在",
      nodeVariableTypeMismatch: "变量节点类型与变量定义不匹配",
      nodeCapabilityUnavailable: "当前后端未提供该节点所需的能力",
      nodeInputValueUnknownPort: "内联值写入了节点定义中不存在的端口",
      nodeInputValueNotAccepted: "该端口不接受内联值",
      nodeRequiredInputMissing: "必填输入既没有连线也没有内联值",
      edgeSelfConnection: "连线的两端指向同一个节点",
      edgeSourceNodeMissing: "连线的起始节点不存在",
      edgeTargetNodeMissing: "连线的目标节点不存在",
      edgeSourcePortMissing: "连线的起始端口不存在",
      edgeTargetPortMissing: "连线的目标端口不存在",
      edgeDirectionInvalid: "连线方向无效，必须从输出连到输入",
      edgeKindMismatch: "连线类别与端口类别不一致",
      edgeTypeIncompatible:
        "端口类型不兼容：{{sourceType}} 无法接到 {{targetType}}",
      edgeCardinalityExceeded: "该端口的连接数超出上限",
    },
    problems: {
      title: "图诊断",
      none: "当前项目没有发现问题。",
      summary: "错误 {{errors}} · 警告 {{warnings}}",
      blocksRun: "存在错误，运行前需要先修复。",
      registryUnavailable: "节点注册表尚未加载，暂时无法校验图。",
      focus: "定位到出问题的元素",
      subject: {
        document: "项目",
        asset: "素材",
        missingGraph: "未知图",
        missingNode: "未知节点",
        missingEdge: "未知连线",
      },
    },
  },
  node: {
    core: {
      flow: {
        start: {
          title: "开始",
          description: "图的执行入口，运行时从这里开始。",
          port: { next: "下一步" },
        },
        stop: {
          title: "结束路径",
          description: "有意结束当前执行路径。",
          port: { run: "执行" },
        },
        endPath: {
          title: "结束路径",
          description:
            "结束当前执行路径；结束单条路径时同时执行的其他分支继续，结束全部路径时在安全节点边界停止所有分支。",
          port: { run: "执行" },
          property: {
            scope: {
              label: "结束范围",
              description: "选择结束当前分支，或在安全节点边界结束全部分支。",
              option: {
                current: "结束单条路径",
                all: "结束全部路径",
              },
            },
          },
        },
        sequence: {
          title: "顺序执行",
          description: "按顺序依次执行连接到步骤端口的分支。",
          port: {
            run: "执行",
            order: "执行顺序",
            steps: "旧版步骤",
            step1: "步骤 1",
            step2: "步骤 2",
            step3: "步骤 3",
            step4: "步骤 4",
            step5: "步骤 5",
            step6: "步骤 6",
            step7: "步骤 7",
            step8: "步骤 8",
            step9: "步骤 9",
            step10: "步骤 10",
            step11: "步骤 11",
            step12: "步骤 12",
            step13: "步骤 13",
            step14: "步骤 14",
            step15: "步骤 15",
            step16: "步骤 16",
          },
        },
        sequenceOrder: {
          title: "更换执行顺序",
          description: "输出已编排的顺序执行步骤列表。",
          port: {
            order: "顺序",
          },
        },
        boundedRetry: {
          title: "有界重试",
          description:
            "按最小轮询间隔重复执行尝试分支，达到超时或次数上限后进入已耗尽分支。",
          port: {
            run: "执行",
            attempt: "开始尝试",
            exhausted: "已耗尽",
            attemptNumber: "尝试次数",
            elapsedMilliseconds: "已用时（毫秒）",
          },
          property: {
            timeoutMilliseconds: {
              label: "超时时间（毫秒）",
              description: "从首次激活开始计算的最长重试时间。",
            },
            rateLimitMilliseconds: {
              label: "轮询间隔（毫秒）",
              description: "相邻两轮尝试开始时间之间的最小间隔。",
            },
            maximumAttempts: {
              label: "最大尝试次数",
              description: "即使尚未超时，也不会超过该次数开始新的尝试。",
            },
          },
        },
        runCounter: {
          title: "运行计数",
          description: "统计本次运行中通过该节点的次数，并按目标次数选择分支。",
          port: {
            run: "执行",
            targetCount: "目标次数",
            currentCount: "当前次数",
            reached: "已达到",
            notReached: "未达到",
          },
        },
        parallel: {
          title: "同时执行",
          description:
            "同时启动两到三个直接步骤；涉及同一设备的操作仍按设备安全规则串行。",
          port: {
            run: "执行",
            branch1: "并行步骤 1",
            branch2: "并行步骤 2",
            branch3: "并行步骤 3",
          },
        },
      },
      function: {
        input: {
          title: "函数输入",
          description: "提供传入当前函数的参数值。",
        },
        return: {
          title: "函数输出",
          description: "返回当前函数选择输出的参数值。",
        },
        call: {
          title: "函数调用",
          description: "调用另一个函数图，并返回它的输出值。",
        },
      },
      value: {
        numberLiteral: {
          title: "数字常量",
          description: "输出一个固定的数值。",
          port: { value: "数值" },
          property: {
            value: {
              label: "数值",
              description: "该节点始终输出的固定数值。",
            },
          },
        },
        stringLiteral: {
          title: "文本常量",
          description: "输出一个固定的文本值。",
          port: { value: "文本" },
          property: {
            value: {
              label: "文本",
              description: "该节点始终输出的固定文本。",
            },
          },
        },
      },
      variable: {
        keyword: {
          variable: "变量",
          get: "获取",
          set: "设置",
        },
        getBool: {
          title: "获取布尔变量",
          description: "读取当前图中的布尔变量值。",
          port: { value: "变量值" },
          property: {
            variableId: {
              label: "变量标识",
              description: "选择要读取的布尔变量。",
            },
          },
        },
        setBool: {
          title: "设置布尔变量",
          description: "将输入的布尔值写入当前图中的变量。",
          port: {
            run: "执行",
            value: "变量值",
            storedValue: "变量值",
            next: "下一步",
          },
          property: {
            variableId: {
              label: "变量标识",
              description: "选择要写入的布尔变量。",
            },
          },
        },
        getNumber: {
          title: "获取数值变量",
          description: "读取当前图中的数值变量。",
          port: { value: "变量值" },
          property: {
            variableId: {
              label: "变量标识",
              description: "选择要读取的数值变量。",
            },
          },
        },
        setNumber: {
          title: "设置数值变量",
          description: "将输入的数值写入当前图中的变量。",
          port: {
            run: "执行",
            value: "变量值",
            storedValue: "变量值",
            next: "下一步",
          },
          property: {
            variableId: {
              label: "变量标识",
              description: "选择要写入的数值变量。",
            },
          },
        },
        getString: {
          title: "获取文本变量",
          description: "读取当前图中的文本变量。",
          port: { value: "变量值" },
          property: {
            variableId: {
              label: "变量标识",
              description: "选择要读取的文本变量。",
            },
          },
        },
        setString: {
          title: "设置文本变量",
          description: "将输入的文本写入当前图中的变量。",
          port: {
            run: "执行",
            value: "变量值",
            storedValue: "变量值",
            next: "下一步",
          },
          property: {
            variableId: {
              label: "变量标识",
              description: "选择要写入的文本变量。",
            },
          },
        },
        getPoint: {
          title: "获取点变量",
          description: "读取当前图中的坐标点变量。",
          port: { value: "变量值" },
          property: {
            variableId: {
              label: "变量标识",
              description: "选择要读取的坐标点变量。",
            },
          },
        },
        setPoint: {
          title: "设置点变量",
          description: "将输入的坐标点写入当前图中的变量。",
          port: {
            run: "执行",
            value: "变量值",
            storedValue: "变量值",
            next: "下一步",
          },
          property: {
            variableId: {
              label: "变量标识",
              description: "选择要写入的坐标点变量。",
            },
          },
        },
        getRect: {
          title: "获取区域变量",
          description: "读取当前图中的区域变量。",
          port: { value: "变量值" },
          property: {
            variableId: {
              label: "变量标识",
              description: "选择要读取的区域变量。",
            },
          },
        },
        setRect: {
          title: "设置区域变量",
          description: "将输入的区域写入当前图中的变量。",
          port: {
            run: "执行",
            value: "变量值",
            storedValue: "变量值",
            next: "下一步",
          },
          property: {
            variableId: {
              label: "变量标识",
              description: "选择要写入的区域变量。",
            },
          },
        },
        getImageRef: {
          title: "获取图像变量",
          description: "读取当前图中的图像变量。",
          port: { value: "变量值" },
          property: {
            variableId: {
              label: "变量标识",
              description: "选择要读取的图像变量。",
            },
          },
        },
        setImageRef: {
          title: "设置图像变量",
          description: "将输入的图像写入当前图中的变量。",
          port: {
            run: "执行",
            value: "变量值",
            storedValue: "变量值",
            next: "下一步",
          },
          property: {
            variableId: {
              label: "变量标识",
              description: "选择要写入的图像变量。",
            },
          },
        },
      },
      image: {
        projectAsset: {
          title: "项目图像",
          description: "从当前项目的截图素材中输出一张图像。",
          port: { image: "图像" },
          property: {
            assetId: {
              label: "图像素材",
              description:
                "按稳定素材标识引用项目中的截图，重命名不会使引用失效。",
            },
          },
        },
      },
      geometry: {
        point: {
          title: "坐标点",
          description: "将参考分辨率中的固定坐标绑定到当前截取画面的坐标空间。",
          port: {
            image: "参考画面",
            x: "X 坐标",
            y: "Y 坐标",
            referenceWidth: "参考宽度",
            referenceHeight: "参考高度",
            point: "坐标点",
          },
        },
        rectangle: {
          title: "矩形区域",
          description: "将参考分辨率中的固定矩形绑定到当前截取画面的坐标空间。",
          port: {
            image: "参考画面",
            x: "X 坐标",
            y: "Y 坐标",
            width: "宽度",
            height: "高度",
            referenceWidth: "参考宽度",
            referenceHeight: "参考高度",
            rectangle: "矩形",
          },
        },
      },
      collection: {
        imageList: {
          title: "多识别图",
          description: "按顺序组合多张图片，供图像识别逐张匹配。",
          port: {
            item1: "图片 1",
            item2: "图片 2",
            item3: "图片 3",
            item4: "图片 4",
            item5: "图片 5",
            item6: "图片 6",
            item7: "图片 7",
            item8: "图片 8",
            item9: "图片 9",
            item10: "图片 10",
            item11: "图片 11",
            item12: "图片 12",
            item13: "图片 13",
            item14: "图片 14",
            item15: "图片 15",
            item16: "图片 16",
            images: "图片列表",
          },
        },
        regionList: {
          title: "多识别区域",
          description: "按顺序组合多个区域，供识别节点逐个匹配。",
          port: {
            item1: "区域 1",
            item2: "区域 2",
            item3: "区域 3",
            item4: "区域 4",
            item5: "区域 5",
            item6: "区域 6",
            item7: "区域 7",
            item8: "区域 8",
            item9: "区域 9",
            item10: "区域 10",
            item11: "区域 11",
            item12: "区域 12",
            item13: "区域 13",
            item14: "区域 14",
            item15: "区域 15",
            item16: "区域 16",
            regions: "区域列表",
          },
        },
        pointList: {
          title: "多点击位置",
          description: "按顺序组合多个点击位置，供点击节点选择或依次执行。",
          port: {
            item1: "位置 1",
            item2: "位置 2",
            item3: "位置 3",
            item4: "位置 4",
            item5: "位置 5",
            item6: "位置 6",
            item7: "位置 7",
            item8: "位置 8",
            item9: "位置 9",
            item10: "位置 10",
            item11: "位置 11",
            item12: "位置 12",
            item13: "位置 13",
            item14: "位置 14",
            item15: "位置 15",
            item16: "位置 16",
            points: "点击位置列表",
          },
        },
      },
      logic: {
        numberCompare: {
          title: "数值比较",
          description: "比较两个数值并输出布尔结果。",
          keyword: { compare: "大于 小于 等于 比较" },
          port: {
            left: "左值",
            right: "右值",
            result: "结果",
            relation: "大小关系",
          },
          property: {
            operator: {
              label: "比较方式",
              description: "决定如何比较左值与右值，结果输出为布尔值。",
              option: {
                greaterThan: "左值大于右值",
                greaterThanOrEqual: "左值大于或等于右值",
                lessThan: "左值小于右值",
                lessThanOrEqual: "左值小于或等于右值",
                equalTo: "左值等于右值",
                notEqualTo: "左值不等于右值",
              },
              optionDescription: {
                greaterThan: "仅当左值大于右值时输出真。",
                greaterThanOrEqual: "左值大于或等于右值时输出真。",
                lessThan: "仅当左值小于右值时输出真。",
                lessThanOrEqual: "左值小于或等于右值时输出真。",
                equalTo: "两个数值相等时输出真。",
                notEqualTo: "两个数值不相等时输出真。",
              },
            },
          },
        },
        numberSelect: {
          title: "判断数值",
          description:
            "从多个输入中选择最大值或最小值；相同数值取最前面的输入。",
          port: {
            a: "A",
            b: "B",
            c: "C",
            d: "D",
            e: "E",
            f: "F",
            g: "G",
            h: "H",
            i: "I",
            j: "J",
            k: "K",
            l: "L",
            m: "M",
            n: "N",
            o: "O",
            p: "P",
            value: "输出数值",
            condition: "输出条件",
          },
          property: {
            mode: {
              label: "判断方式",
              description: "选择输出全部输入中的最大值或最小值。",
              option: { maximum: "最大", minimum: "最小" },
            },
          },
        },
        branch: {
          title: "判断分支",
          description: "根据布尔条件选择继续执行的分支。",
          port: {
            run: "执行",
            condition: "条件",
            whenTrue: "为真时",
            whenFalse: "为假时",
          },
        },
        taskChoice: {
          title: "任务选择",
          description:
            "根据当前任务设置选择一个可执行分支；找不到对应选项时从未匹配端口继续。",
          port: {
            run: "执行",
            selectedCaseId: "选项标识",
            case: "候选选项",
            unmatched: "未匹配",
          },
          property: {
            selectedCaseId: {
              label: "当前选项",
              description: "选择要执行的稳定选项标识。",
            },
            settingKey: {
              label: "设置标识",
              description: "顶部任务设置使用的稳定内部标识。",
            },
            exposeInTaskSettings: {
              label: "显示在任务设置",
              description: "开启后，当前任务顶部会显示这个选择。",
            },
          },
        },
        caseOverlayBool: {
          title: "布尔选项覆盖",
          description: "有选中选项值时使用该值，否则使用回退值。",
          port: {
            selectedCaseId: "选项标识",
            fallback: "回退值",
            case: "选项值",
            value: "结果",
          },
        },
        caseOverlayNumber: {
          title: "数值选项覆盖",
          description: "有选中选项数值时使用该值，否则使用回退数值。",
          port: {
            selectedCaseId: "选项标识",
            fallback: "回退值",
            case: "选项值",
            value: "结果",
          },
        },
        caseOverlayImageRef: {
          title: "图片选项覆盖",
          description: "有选中选项图片时使用该图片，否则使用回退图片。",
          port: {
            selectedCaseId: "选项标识",
            fallback: "回退图片",
            case: "选项图片",
            value: "图片",
          },
        },
      },
      math: {
        expression: {
          title: "运算数值",
          description: "使用 A、B、C 等输入和 +、−、×、÷、括号计算有限数值。",
          port: {
            a: "A",
            b: "B",
            c: "C",
            d: "D",
            e: "E",
            f: "F",
            g: "G",
            h: "H",
            i: "I",
            j: "J",
            k: "K",
            l: "L",
            m: "M",
            n: "N",
            o: "O",
            p: "P",
            result: "输出数值",
          },
          property: {
            expression: {
              label: "运算表达式",
              description: "只允许输入 A 至 P、有限数字、+-*/ 和括号。",
            },
          },
        },
        arithmetic: {
          title: "数值运算",
          description: "对两个有限数值执行加、减、乘或除运算。",
          port: { left: "左值", right: "右值", result: "结果" },
          property: {
            operator: {
              label: "运算符",
              description: "选择左值和右值之间的运算。",
              option: {
                add: "加法（+）",
                subtract: "减法（−）",
                multiply: "乘法（×）",
                divide: "除法（÷）",
              },
              optionDescription: {
                add: "计算左值加右值。",
                subtract: "计算左值减右值。",
                multiply: "计算左值乘右值。",
                divide: "计算左值除以右值；右值不能为零。",
              },
            },
          },
        },
      },
      time: {
        delay: {
          title: "等待延迟",
          description: "等待一段有上限的时间后继续执行。",
          port: {
            run: "执行",
            durationMilliseconds: "时长（毫秒）",
            next: "下一步",
          },
        },
      },
      diagnostic: {
        log: {
          title: "输出日志",
          description: "向当前运行日志添加一条有长度限制的消息。",
          port: {
            run: "执行",
            message: "消息",
            textPart: "文本片段",
            numberPart: "数值片段",
            next: "下一步",
          },
          property: {
            segmentKinds: {
              label: "片段类型",
              description: "按顺序拼接文本或数值片段。",
            },
            appendNewline: {
              label: "末尾换行",
              description: "在本条日志末尾添加换行。",
            },
          },
        },
      },
    },
    automation: {
      captureScreen: {
        title: "截取画面",
        description: "从当前设备截取一帧画面。",
        port: {
          run: "执行",
          image: "画面",
          width: "宽度",
          height: "高度",
          next: "下一步",
        },
      },
      clickRectCenter: {
        title: "点击矩形中心",
        description: "调整识别矩形后，点击调整结果的中心坐标。",
        port: {
          run: "执行",
          rect: "矩形",
          offsetX: "水平偏移",
          offsetY: "垂直偏移",
          offsetWidth: "宽度调整",
          offsetHeight: "高度调整",
          clicked: "已点击",
          next: "下一步",
          failed: "已确认失败",
        },
        property: {
          offsetX: {
            label: "水平偏移",
            description: "在识别矩形的 X 坐标上增加此像素值。",
          },
          offsetY: {
            label: "垂直偏移",
            description: "在识别矩形的 Y 坐标上增加此像素值。",
          },
          offsetWidth: {
            label: "宽度调整",
            description: "在识别矩形的宽度上增加此像素值。",
          },
          offsetHeight: {
            label: "高度调整",
            description: "在识别矩形的高度上增加此像素值。",
          },
        },
      },
      clickPoint: {
        title: "点击",
        description: "点击单个位置、多个位置或指定矩形中的位置。",
        port: {
          run: "执行",
          point: "坐标点",
          image: "参考画面",
          points: "多个位置",
          rect: "点击区域",
          x: "X 坐标",
          y: "Y 坐标",
          referenceWidth: "参考宽度",
          referenceHeight: "参考高度",
          clicked: "已点击",
          clickedCount: "点击数量",
          selectedIndex: "选中序号",
          next: "下一步",
          failed: "已确认失败",
        },
        property: {
          inputMode: {
            label: "坐标来源",
            description: "选择单点、多点或矩形区域点击方式。",
            option: {
              point: "单个位置",
              coordinates: "直接坐标",
              randomPoints: "随机一个位置",
              sequentialPoints: "按顺序全部点击",
              rectCenter: "点击区域中心",
              rectRandom: "点击区域随机位置",
            },
            optionDescription: {
              point: "从其他节点接收一个坐标点。",
              coordinates: "直接填写坐标，或从模拟器画面取点。",
              randomPoints: "从多个位置中随机选择一个。",
              sequentialPoints: "按顺序点击全部位置。",
              rectCenter: "点击矩形区域的中心。",
              rectRandom: "在矩形区域内随机选择一个像素位置。",
            },
          },
          intervalMilliseconds: {
            label: "点击间隔（毫秒）",
            description: "按顺序点击多个位置时，两次点击之间的等待时间。",
          },
        },
      },
      launchAndroidApp: {
        title: "启动 Android 应用",
        description: "在当前设备上启动已明确指定的应用组件。",
        port: {
          run: "执行",
          launched: "已启动",
          next: "下一步",
        },
        property: {
          intent: {
            label: "应用标识",
            description:
              "填写包名，或填写包名/Activity；不支持额外参数或命令。",
          },
        },
      },
      pressAndroidKey: {
        title: "发送 Android 按键",
        description: "向当前设备发送一个受支持的语义按键。",
        port: {
          run: "执行",
          pressed: "已发送",
          next: "下一步",
        },
        property: {
          key: {
            label: "按键",
            description: "当前版本仅支持 Escape，用于关闭应用内弹层。",
            option: { escape: "Escape" },
            optionDescription: { escape: "发送 Android Escape 按键。" },
          },
        },
      },
      swipe: {
        title: "滑动",
        description: "使用一个触点在当前设备上执行一次显式滑动。",
        port: {
          run: "执行",
          start: "起点",
          end: "终点",
          completed: "已完成",
          next: "下一步",
          failed: "已确认失败",
        },
        property: {
          durationMilliseconds: {
            label: "滑动时长（毫秒）",
            description: "从起点移动到终点的时间，范围为 1 至 60000 毫秒。",
          },
        },
      },
      touchAction: {
        title: "触控动作",
        description: "在当前设备画面上执行点击、长按、滑动或双指滑动。",
        port: {
          run: "执行",
          start: "起点 / 点击点",
          end: "终点",
          secondaryStart: "第二触点起点",
          secondaryEnd: "第二触点终点",
          completed: "已完成",
          next: "下一步",
        },
        property: {
          actionType: {
            label: "动作类型",
            description: "选择要发送到设备的触控动作。",
            option: {
              click: "点击",
              longPress: "长按",
              swipe: "滑动",
              multiSwipe: "多指滑动（双指）",
            },
            optionDescription: {
              click: "在一个坐标点执行一次点击。",
              longPress: "在起点保持按下指定时长。",
              swipe: "从起点移动到终点。",
              multiSwipe: "同时移动两个触点。",
            },
          },
          longPressDurationMilliseconds: {
            label: "长按时长（毫秒）",
            description: "触点保持按下的时间，范围为 1 至 60000 毫秒。",
          },
          swipeDurationMilliseconds: {
            label: "滑动时长（毫秒）",
            description: "从起点移动到终点的时间，范围为 1 至 60000 毫秒。",
          },
          secondaryStartDelayMilliseconds: {
            label: "第二触点延迟（毫秒）",
            description: "双指滑动时第二个触点晚于第一个触点按下的时间。",
          },
        },
        hint: {
          click: "连接起点即可执行点击。",
          longPress: "连接起点，并设置长按时长。",
          swipe: "连接起点和终点，并设置滑动时长。",
          multiSwipe: "连接两组起点和终点；当前版本支持两个触点。",
        },
      },
    },
    vision: {
      ocr: {
        title: "文字识别",
        description: "在画面或指定区域内识别文字。",
        port: {
          run: "执行",
          image: "画面",
          roi: "识别区域",
          regions: "多识别区域",
          confidenceThreshold: "最低置信度",
          result: "识别结果",
          matched: "是否识别",
          bestText: "最佳文本",
          bestConfidence: "输出数值",
          matchedRegionIndex: "命中区域序号",
          bestRect: "最佳区域",
          next: "下一步",
        },
        property: {
          confidenceThreshold: {
            label: "最低置信度",
            description: "只保留置信度达到该阈值的文字候选。",
          },
          expected: {
            label: "期望文本正则",
            description:
              "按列表顺序优先选择匹配正则表达式的文字；留空时使用默认排序。",
          },
        },
      },
      templateMatch: {
        title: "模板匹配",
        description: "在图像中查找与模板图相似的区域。",
        port: {
          run: "运行",
          image: "目标图像",
          template: "模板图像",
          templates: "多识别图",
          roi: "识别区域",
          regions: "多识别区域",
          threshold: "最低相似度",
          matched: "是否匹配",
          bestRect: "最佳区域",
          bestScore: "最佳分数",
          matchedRegionIndex: "命中区域序号",
          matchedTemplate: "命中图片",
          matchedTemplateIndex: "命中图片序号",
          rects: "匹配区域",
          scores: "匹配分数",
          next: "下一步",
        },
        property: {
          threshold: {
            label: "最低相似度",
            description: "只保留达到该相似度的模板匹配结果。",
          },
          method: {
            label: "匹配方法",
            description: "选择模板像素的比较方式。",
            option: {
              normalizedCoefficient: "归一化相关系数",
              coefficient: "相关系数",
              rgbDifference: "RGB 色差",
            },
            optionDescription: {
              normalizedCoefficient: "对亮度变化更稳健的归一化相关比较。",
              coefficient: "直接比较模板与目标的相关程度。",
              rgbDifference: "按 RGB 通道差异比较像素。",
            },
          },
          greenMask: {
            label: "绿色遮罩",
            description: "将模板中的纯绿色区域作为透明遮罩。",
          },
        },
      },
      featureMatch: {
        title: "特征匹配",
        description: "使用局部特征在图像中查找经过缩放或旋转的目标。",
        port: {
          run: "运行",
          image: "目标图像",
          template: "模板图像",
          templates: "多识别图",
          roi: "识别区域",
          regions: "多识别区域",
          matched: "是否匹配",
          bestRect: "最佳区域",
          bestCount: "最佳特征数",
          matchedRegionIndex: "命中区域序号",
          matchedTemplate: "命中图片",
          matchedTemplateIndex: "命中图片序号",
          rects: "匹配区域",
          counts: "特征数量",
          next: "下一步",
        },
        property: {
          detector: {
            label: "特征检测器",
            description: "选择用于提取和比较局部特征的算法。",
            option: {
              SIFT: "SIFT",
              KAZE: "KAZE",
              AKAZE: "AKAZE",
              BRISK: "BRISK",
              ORB: "ORB",
            },
            optionDescription: {
              SIFT: "精度较高，适合需要稳定特征的目标。",
              KAZE: "在非线性尺度空间中提取特征。",
              AKAZE: "速度和特征稳定性的折中选择。",
              BRISK: "速度较快，适合资源有限的场景。",
              ORB: "速度快，适合一般实时识别。",
            },
          },
          minimumCount: {
            label: "最少特征数",
            description: "至少需要多少个可靠特征对应关系。",
          },
          ratio: {
            label: "距离比率",
            description: "较小的值会更严格地排除模糊特征。",
          },
          greenMask: {
            label: "绿色遮罩",
            description: "将模板中的纯绿色区域作为透明遮罩。",
          },
        },
      },
      colorMatch: {
        title: "颜色匹配",
        description: "查找落在指定颜色范围内的像素区域。",
        port: {
          run: "运行",
          image: "目标图像",
          roi: "识别区域",
          regions: "多识别区域",
          matched: "是否匹配",
          bestRect: "最佳区域",
          bestCount: "最佳像素数",
          matchedRegionIndex: "命中区域序号",
          rects: "匹配区域",
          counts: "像素数量",
          next: "下一步",
        },
        property: {
          method: {
            label: "颜色空间",
            description: "选择颜色范围采用的通道类型。灰度模式只使用第一通道。",
            option: { RGB: "RGB", HSV: "HSV", GRAY: "灰度" },
            optionDescription: {
              RGB: "直接使用红、绿、蓝三个通道。",
              HSV: "按色相、饱和度和明度筛选颜色。",
              GRAY: "只使用灰度通道进行匹配。",
            },
          },
          lower1: { label: "下限通道 1", description: "第一通道的最小值。" },
          lower2: { label: "下限通道 2", description: "第二通道的最小值。" },
          lower3: { label: "下限通道 3", description: "第三通道的最小值。" },
          upper1: { label: "上限通道 1", description: "第一通道的最大值。" },
          upper2: { label: "上限通道 2", description: "第二通道的最大值。" },
          upper3: { label: "上限通道 3", description: "第三通道的最大值。" },
          minimumCount: {
            label: "最少像素数",
            description: "达到颜色范围的像素数量下限。",
          },
          connected: {
            label: "合并连续区域",
            description: "将相邻的命中像素合并为连续区域。",
          },
        },
      },
    },
    text: {
      parseNumber: {
        title: "解析数字",
        description: "按照明确的分隔符规则将文本解析为有限数值。",
        port: {
          run: "执行",
          text: "文本",
          number: "数值",
          normalizedText: "规范化文本",
          parsed: "解析成功",
          invalid: "无效",
        },
        property: {
          decimalSeparator: {
            label: "小数分隔符",
            description: "小数部分前使用的明确分隔符。",
          },
          groupingSeparator: {
            label: "千位分隔符",
            description: "明确的千位分组符，也可设为无。",
          },
          normalizeFullWidth: {
            label: "规范化全角数字",
            description: "解析前转换全角数字和分隔符。",
          },
          allowSign: {
            label: "允许正负号",
            description: "接受可选的前置加号或减号。",
          },
          minimum: {
            label: "最小值",
            description: "解析值低于该可选边界时判为无效。",
          },
          maximum: {
            label: "最大值",
            description: "解析值高于该可选边界时判为无效。",
          },
        },
      },
      readText: {
        title: "读取文本",
        description: "按空间阅读顺序读取指定序号的文字识别候选。",
        port: {
          run: "执行",
          result: "识别结果",
          text: "文本",
          rect: "文本区域",
          selected: "已读取",
          missing: "序号不存在",
        },
        property: {
          candidateIndex: {
            label: "读取第几个",
            description: "从 1 开始选择要输出的识别候选。",
          },
          readingOrder: {
            label: "阅读顺序",
            description: "矩阵结果按所选主方向排序，再按另一方向推进。",
            option: {
              rowMajor: "从左到右，再从上到下",
              columnMajor: "从上到下，再从左到右",
            },
            optionDescription: {
              rowMajor: "先按每行从左到右读取，再进入下一行。",
              columnMajor: "先按每列从上到下读取，再进入下一列。",
            },
          },
        },
      },
      readNumber: {
        title: "读取数值",
        description: "按空间阅读顺序读取指定候选，并按明确格式解析为有限数值。",
        port: {
          run: "执行",
          result: "识别结果",
          number: "数值",
          normalizedText: "规范化文本",
          rect: "文本区域",
          selected: "已读取",
          missing: "序号不存在",
          invalid: "不是有效数值",
        },
        property: {
          candidateIndex: {
            label: "读取第几个",
            description: "从 1 开始选择要解析的识别候选。",
          },
          readingOrder: {
            label: "阅读顺序",
            description: "矩阵结果按所选主方向排序，再按另一方向推进。",
            option: {
              rowMajor: "从左到右，再从上到下",
              columnMajor: "从上到下，再从左到右",
            },
            optionDescription: {
              rowMajor: "先按每行从左到右读取，再进入下一行。",
              columnMajor: "先按每列从上到下读取，再进入下一列。",
            },
          },
          decimalSeparator: {
            label: "小数分隔符",
            description: "小数部分前使用的明确分隔符。",
            option: { ".": "点（.）", ",": "逗号（,）" },
            optionDescription: {
              ".": "使用点号作为小数部分分隔符。",
              ",": "使用逗号作为小数部分分隔符。",
            },
          },
          groupingSeparator: {
            label: "千位分隔符",
            description: "明确的千位分组符，也可设为无。",
            option: {
              "": "无",
              ".": "点（.）",
              ",": "逗号（,）",
              " ": "空格",
            },
            optionDescription: {
              "": "不使用千位分组符。",
              ".": "使用点号分隔千位。",
              ",": "使用逗号分隔千位。",
              " ": "使用空格分隔千位。",
            },
          },
          normalizeFullWidth: {
            label: "规范化全角数字",
            description: "解析前转换全角数字和分隔符。",
          },
          allowSign: {
            label: "允许正负号",
            description: "接受可选的前置加号或减号。",
          },
          minimum: { label: "最小值", description: "可选的数值下界。" },
          maximum: { label: "最大值", description: "可选的数值上界。" },
        },
      },
      readValue: {
        title: "输出数值",
        description: "从文字识别结果中读取文本或数值，并按位置或阅读顺序输出。",
        port: {
          run: "执行",
          result: "识别结果",
          text: "文本",
          texts: "文本列表",
          number: "数值",
          numbers: "数值列表",
          rect: "区域",
          rects: "区域列表",
          selected: "已读取",
          missing: "未找到",
          invalid: "无效",
        },
        property: {
          valueMode: {
            label: "读取内容",
            description: "选择输出识别到的文本，或解析为数值。",
            option: { text: "文本", number: "数字" },
            optionDescription: {
              text: "直接输出识别到的文字内容。",
              number: "将识别内容解析为有限数值。",
            },
          },
          numberType: {
            label: "数字类型",
            description: "选择数值解析必须满足的类型约束。",
            option: {
              integer: "整数",
              float: "浮点数",
              percentage: "百分比",
              positive: "正数",
              unsignedInteger: "无符号整数",
            },
            optionDescription: {
              integer: "允许正负号的有限整数。",
              float: "任意有限数值。",
              percentage: "要求带百分号，并输出除以 100 后的数值。",
              positive: "必须大于零的数值。",
              unsignedInteger: "大于等于零的整数。",
            },
          },
          selectionMode: {
            label: "输出位置",
            description: "选择输出全部候选，或指定行和项。",
            option: { all: "全部", position: "指定位置" },
            optionDescription: {
              all: "按阅读顺序输出所有有效候选。",
              position: "只输出指定行和指定项的候选。",
            },
          },
          readingOrder: {
            label: "读取顺序",
            description: "选择先按行还是先按列整理识别结果。",
            option: { rowMajor: "按行", columnMajor: "按列" },
            optionDescription: {
              rowMajor: "从左到右读取一行，再读取下一行。",
              columnMajor: "从上到下读取一列，再读取下一列。",
            },
          },
          lineIndex: {
            label: "第几行",
            description: "从 1 开始指定要读取的行。",
          },
          itemIndex: {
            label: "第几个",
            description: "从 1 开始指定该行或列中的第几个候选。",
          },
          decimalSeparator: {
            label: "小数分隔符",
            description: "小数部分前使用的明确分隔符。",
            option: { ".": "点（.）", ",": "逗号（,）" },
            optionDescription: {
              ".": "使用点号作为小数部分分隔符。",
              ",": "使用逗号作为小数部分分隔符。",
            },
          },
          groupingSeparator: {
            label: "千位分隔符",
            description: "明确的千位分组符，也可设为无。",
            option: {
              "": "无",
              ".": "点（.）",
              ",": "逗号（,）",
              " ": "空格",
            },
            optionDescription: {
              "": "不使用千位分组符。",
              ".": "使用点号分隔千位。",
              ",": "使用逗号分隔千位。",
              " ": "使用空格分隔千位。",
            },
          },
          normalizeFullWidth: {
            label: "规范化全角数字",
            description: "解析前转换全角数字和分隔符。",
          },
          allowSign: {
            label: "允许正负号",
            description: "接受可选的前置加号或减号。",
          },
          minimum: { label: "最小值", description: "可选的数值下界。" },
          maximum: { label: "最大值", description: "可选的数值上界。" },
        },
      },
    },
    test: {
      fake: {
        ocr: {
          title: "模拟文字识别",
          description: "为运行时测试返回确定的文字结果。",
          port: {
            run: "执行",
            fixtureText: "测试文本",
            matched: "是否命中",
            text: "文本",
            next: "下一步",
          },
          property: {
            matched: {
              label: "返回命中",
              description: "控制模拟识别器是否报告识别成功。",
            },
          },
        },
        action: {
          title: "模拟操作",
          description: "为运行时测试记录一次确定的操作。",
          port: {
            run: "执行",
            label: "标签",
            recorded: "已记录",
            next: "下一步",
          },
        },
      },
    },
  },
  workflowGroup: {
    imageRecognition: {
      title: "图像识别模板",
      description: "截取当前画面，并选择模板、特征或颜色匹配方式。",
      method: "匹配方式",
      methodDescription:
        "选择用于查找目标的识别方式；不同方式对模板、颜色和缩放变化的敏感度不同。",
      methods: {
        template: "模板匹配",
        feature: "特征匹配",
        color: "颜色匹配",
      },
      methodOptionDescription: {
        template: "适合外观和尺寸相对稳定的目标，需要模板图像。",
        feature: "允许一定缩放或旋转，需要目标包含足够的局部特征。",
        color: "按颜色范围查找区域，不需要模板图像。",
      },
      templateAsset: "模板图像",
      templateAssetDescription:
        "选择项目中保存的模板画面；颜色匹配不需要模板。",
      templatePlaceholder: "选择项目截图",
      templateNotUsed: "颜色匹配不需要模板图像。",
      noTemplateAssets: "请先从右侧设备画面截取并保存模板。",
      matchThreshold: "模板匹配阈值",
      matchThresholdDescription:
        "仅保留匹配分数达到该阈值的区域，范围为 0 到 1，默认 0.7。",
      region: "限定识别区域",
      regionDescription: "启用后只在指定矩形内匹配；关闭时使用完整画面。",
      pickRegion: "从画面选择",
      regionField: {
        x: "X",
        y: "Y",
        width: "宽",
        height: "高",
        referenceWidth: "屏幕宽",
        referenceHeight: "屏幕高",
      },
      port: {
        run: "执行",
        template: "模板图像",
        templates: "多识别图",
        roi: "识别区域",
        regions: "多识别区域",
        matched: "是否匹配",
        matchValue: "输出数值",
        matchedRegionIndex: "命中区域序号",
        matchedTemplateIndex: "命中图片序号",
        result: "识别结果",
        bestText: "最佳文字",
        bestRect: "最佳区域",
        image: "当前画面",
        noMatch: "未匹配",
        next: "下一步",
      },
    },
    textRecognition: {
      title: "文字识别模板",
      description: "等待并截取画面，执行 OCR，再按识别结果选择点击方式。",
      clickMethod: "点击方式",
      clickMethodDescription: "决定识别成功后是否点击识别区域中心或指定坐标。",
      clickMethods: {
        none: "不点击",
        rectCenter: "点击识别框中心",
        point: "点击指定坐标",
      },
      clickMethodOptionDescription: {
        none: "只输出识别结果，不执行设备点击。",
        rectCenter: "点击当前最佳文字候选所在区域的中心。",
        point: "点击组合节点中保存的指定坐标。",
      },
      beforeDelay: "识别前延迟（毫秒）",
      afterDelay: "点击后延迟（毫秒）",
      confidenceThreshold: "最低置信度",
      confidenceThresholdDescription: "低于此阈值的文字候选会被忽略。",
      region: "限定识别区域",
      regionDescription: "启用后只在指定矩形内识别文字；关闭时使用完整画面。",
      pickRegion: "从画面选择",
      clickPoint: "指定点击坐标",
      clickPointDescription: "设置识别成功后要点击的固定坐标。",
      pickPoint: "从画面选择",
      regionField: {
        x: "X",
        y: "Y",
        width: "宽",
        height: "高",
        referenceWidth: "屏幕宽",
        referenceHeight: "屏幕高",
      },
      pointField: {
        x: "X",
        y: "Y",
        referenceWidth: "屏幕宽",
        referenceHeight: "屏幕高",
      },
      port: {
        run: "执行",
        beforeDelayMilliseconds: "识别前延迟",
        roi: "识别区域",
        regions: "多识别区域",
        afterDelayMilliseconds: "点击后延迟",
        clickPoint: "点击坐标",
        matched: "是否识别",
        matchValue: "输出数值",
        matchedRegionIndex: "命中区域序号",
        result: "识别结果",
        bestText: "最佳文字",
        bestRect: "最佳区域",
        image: "当前画面",
        noMatch: "未识别到",
        next: "下一步",
      },
    },
    recognition: {
      clickEnabled: "识别成功后点击",
      clickEnabledDescription:
        "开启后才显示点击方式和点击位置；关闭时只返回识别结果。",
      delayMode: "延迟位置",
      delayModeDescription: "选择等待发生在识别前，还是识别成功后、点击前。",
      delayBeforeRecognition: "延迟后识别",
      delayBeforeRecognitionDescription: "先等待，再截取画面并开始识别。",
      delayBeforeClick: "识别成功后延迟点击",
      delayBeforeClickDescription: "识别成功后等待，再执行点击动作。",
      delayMilliseconds: "延迟（毫秒）",
      delayMillisecondsDescription: "等待时长，取值范围由节点运行时限制。",
    },
    actions: {
      expand: "展开组合节点",
      collapse: "折叠组合节点",
      promoteInput: "拆分为连接节点",
      revealParameterNode: "显示已连接的参数节点",
    },
    coordinateDetails: "坐标详情",
    steps: "执行步骤",
    stepCount: "执行步骤（{{count}}）",
  },
  template: {
    recognizeNumberAndBranch: {
      title: "识别数值并分支",
      description: "识别画面中的数值，与阈值比较后选择分支。",
      port: {
        run: "执行",
        next: "下一步",
      },
    },
    compareNumbersAndBranch: {
      title: "比较数值并分支",
      description:
        "插入相互独立并已连接的开始、数值比较和条件分支节点，仍可自由编辑。",
    },
    captureAndClickPoint: {
      title: "截取画面并点击坐标",
      description:
        "插入开始、截取画面、坐标点和点击坐标节点；选择坐标后即可运行。",
    },
  },
  publishing: {
    action: {
      open: "导出与发布",
    },
    dialog: {
      title: "导出与发布项目",
      description:
        "可将签名项目资源或包含最新版 Rino_WFP 的可运行 Windows 应用导出到本地，也可发布为 GitHub Release 资产。",
      publicNotice:
        "发布会把已保存的项目图、项目元数据和项目素材公开上传到 GitHub；应用模式还会上传公开的 Rino_WFP 运行文件。不会上传恢复数据、日志、本机路径、凭据或编辑器设置。",
      authTitle: "GitHub CLI 授权",
      authDescription:
        "登录由官方 GitHub CLI 发起浏览器/设备授权流程。Rino 不读取、存储或显示 GitHub 账户标识或令牌，凭据由 GH CLI 管理。",
      authFlow:
        "按 GH CLI 提示打开官方浏览器授权页面；一次性代码会复制到剪贴板，按提示粘贴即可。",
      logoutWarning:
        "这只会移除本机 GH CLI 的登录配置，不会撤销远程 OAuth 令牌。确认要退出吗？",
      exportResourceTitle: "选择 Rino_WFP 资源目录",
      resourceFileTypeLabel: "RinoProject 资源目录",
      exportApplicationTitle: "导出 Rino Windows 应用",
      applicationFileTypeLabel: "Rino 应用 ZIP",
    },
    content: {
      resource: "仅导出资源",
      resourceDescription:
        "本地导出会在所选目录生成签名的 RinoProject 文件夹；GitHub 发布仍使用兼容的 .rino-package。",
      application: "导出可运行应用",
      applicationDescription:
        "把签名资源包放入 Rino_WFP、Sidecar、ADB 与固定 OCR 资源中，生成 Windows 应用 ZIP。",
    },
    fields: {
      content: "导出内容",
      updateWfp: "本地导出前同步最新 Rino_WFP",
      updateWfpNotice:
        "未勾选时优先使用已验证缓存；缓存不存在仍会同步。发布到 GitHub 的应用始终强制同步最新稳定版。",
      packageId: "包标识",
      version: "版本",
      summary: "项目摘要",
      publisherId: "项目包命名空间（自声明）",
      publisherName: "项目包署名（自声明）",
      license: "许可证标识",
      githubOwner: "GitHub 所有者",
      githubRepository: "GitHub 仓库",
      metadataNotice:
        "项目包命名空间和署名只是自声明信息，不代表 GitHub 身份或验证。仓库和上传身份由当前 GH CLI 登录决定；所有者与仓库文本只选择目标，发布时会按权限检查。",
    },
    status: {
      checking: "正在检查 GitHub CLI 登录状态…",
      authenticated: "GitHub CLI 已认证",
      loginRequired:
        "GitHub CLI 尚未登录。点击登录并按官方浏览器/设备流程完成授权。",
      cliRequired:
        "未找到 GitHub CLI。仍可导出本地资源包；需要刷新 Rino_WFP 的应用导出不可用。",
    },
    actions: {
      login: "登录 GitHub CLI",
      loggingIn: "正在登录…",
      logout: "退出 GitHub CLI",
      loggingOut: "正在退出…",
      logoutConfirm: "确认退出",
      logoutCancel: "取消",
      export: "导出到本地",
      exporting: "正在导出…",
      publish: "一键发布到 GitHub",
      publishing: "正在发布…",
    },
    result: {
      resourceExported: "资源目录已导出",
      resourcePublished: "资源包已发布",
      applicationExported: "可运行应用已导出",
      applicationPublished: "可运行应用已发布",
      keyId: "签名密钥：{{keyId}}",
      publicKey: "发布者公钥：{{publicKey}}",
    },
    errors: {
      NO_OPEN_PROJECT: "没有打开的项目。",
      DIALOG_UNAVAILABLE: "无法打开系统保存对话框。",
      INVALID_INPUT: "发布信息格式不正确，请检查标识、版本和仓库名称。",
      INVALID_PROJECT: "当前项目无法生成有效的发布包。",
      ASSET_UNAVAILABLE: "项目素材缺失、损坏或与登记的哈希不一致。",
      CREDENTIAL_UNAVAILABLE: "无法访问 Windows 凭据管理器中的本地签名密钥。",
      PACKAGE_WRITE_FAILED: "项目保存或项目包写入失败。",
      APPLICATION_WRITE_FAILED: "无法生成或验证可运行应用 ZIP。",
      WFP_TEMPLATE_UNAVAILABLE:
        "Rino_WFP 仓库尚无可用的最新稳定模板，且本机没有已验证缓存。",
      WFP_TEMPLATE_INVALID: "Rino_WFP 模板的清单、路径或完整性校验失败。",
      WFP_TEMPLATE_SYNC_FAILED:
        "无法从 miaoyu2233/Rino_WFP 同步最新稳定模板，请检查 GH CLI 与网络后重试。",
      CACHE_CLEANUP_FAILED:
        "发布临时文件未能安全清理。若刚完成上传，请不要重复发布同一版本；重新启动应用后再检查。",
      GITHUB_CLI_UNAVAILABLE: "未找到 GitHub CLI。",
      GITHUB_AUTHENTICATION_REQUIRED:
        "GitHub CLI 尚未登录。请先在终端运行 gh auth login。",
      GITHUB_AUTHENTICATION_FAILED:
        "GitHub CLI 浏览器/设备登录未完成或失败。请重试并按提示完成授权。",
      GITHUB_LOGOUT_FAILED:
        "无法移除本机 GitHub CLI 登录配置。请运行 gh auth status 后重试。",
      PACKAGE_VERSION_EXISTS:
        "该版本的发布资产已经存在。已发布资产不可覆盖，请提升版本号后重试。",
      GITHUB_COMMAND_FAILED:
        "GitHub 仓库或 Release 操作失败。请检查权限、仓库状态和网络后重试。",
      DESKTOP_COMMAND_FAILED: "桌面发布服务不可用。",
    },
  },
  project: {
    action: {
      new: "新建项目",
      open: "打开项目",
      save: "保存项目",
      saveAs: "另存为",
      close: "关闭项目",
    },
    identity: {
      unsavedMarker: "有未保存的更改",
      locationTooltip: "项目位置：{{path}}",
      savingStatus: "正在写入项目文件",
    },
    dialog: {
      chooseLocationTitle: "选择一个空文件夹作为项目位置",
      openTitle: "打开 Rino 项目",
      manifestFileTypeLabel: "Rino 项目清单",
    },
    unsaved: {
      title: "当前项目有未保存的更改",
      description: "继续之前，可以先保存这些更改，或者放弃它们。",
      save: "保存后继续",
      discard: "放弃更改",
    },
    recovery: {
      title: "发现未保存的工作",
      description:
        "上次退出时这个项目还有未写入磁盘的更改。可以恢复这份内容，或者继续使用磁盘上的版本。",
      restore: "恢复未保存的内容",
      discard: "使用磁盘上的版本",
    },
    problem: {
      unavailableTitle: "项目文件服务不可用",
      unavailableDescription:
        "当前运行环境没有桌面外壳，无法读写项目文件。请在 Rino 桌面应用中操作。",
      commandFailedTitle: "项目操作未完成",
      formatRejectedTitle: "项目文件未通过校验",
    },
    error: {
      NO_OPEN_PROJECT: "当前没有打开的项目。",
      NO_CHOSEN_LOCATION: "没有选择项目位置，操作已取消。",
      LOCATION_ALREADY_HOLDS_PROJECT:
        "所选文件夹里已经有一个 Rino 项目。请改用“打开项目”，或另选一个空文件夹。",
      LOCATION_NOT_EMPTY:
        "所选文件夹不是空的。请另选一个空文件夹，以免覆盖已有文件。",
      NOT_A_PROJECT_MANIFEST: "所选文件不是 project.rino.json 项目清单。",
      UNSUPPORTED_FILE_NAME: "项目里出现了本格式不允许的文件名，操作已中止。",
      FILE_TOO_LARGE: "项目文件超过了允许的大小上限，操作已中止。",
      TOO_MANY_FILES: "项目包含的文件数量超过了上限，操作已中止。",
      READ_FAILED: "无法读取项目文件。请确认文件仍然存在且有读取权限。",
      WRITE_FAILED:
        "无法写入项目文件，磁盘上的原文件保持不变。请确认有写入权限。",
      CREATE_FAILED: "无法创建项目目录。请确认所选位置有写入权限。",
      INVALID_JSON: "写入的内容不是有效 JSON，改动没有提交。",
      INVALID_IMAGE: "截图内容与其尺寸或格式信息不一致，素材没有写入。",
      CAPTURE_UNAVAILABLE: "截图已失效或已被释放，请从当前设备画面重新截图。",
      DIALOG_UNAVAILABLE: "无法打开系统文件对话框。",
      DESKTOP_COMMAND_FAILED: "桌面外壳没有返回结构化的失败信息。",
    },
    format: {
      notJson: "{{fileName}} 不是有效的 JSON 文件。",
      invalidShape: "{{fileName}} 的结构不符合项目格式。",
      unsupportedVersion:
        "该项目使用第 {{foundVersion}} 版格式，当前版本的 Rino 无法读取。请升级 Rino 后再打开，文件未被改动。",
      graphFileMissing: "项目清单引用的图文件 {{fileName}} 不存在。",
      graphFileMismatch: "图文件 {{fileName}} 属于另一个项目或另一张图。",
      duplicateGraphEntry: "项目清单里重复登记了 {{fileName}}。",
      entryGraphMissing: "项目清单指定的入口图不在图列表中。",
      duplicateAssetName: "素材名称“{{displayName}}”与另一条素材重名。",
      documentInvalid: "组装出的项目文档不符合规范。",
    },
  },
  runtime: {
    states: {
      connecting: "正在连接运行时",
      unavailable: "运行时不可用",
      stopped: "运行时已停止",
      starting: "运行时启动中",
      handshaking: "正在协商协议",
      ready: "运行时就绪",
      degraded: "运行时已降级",
      restarting: "运行时重启中",
      stopping: "运行时停止中",
      failed: "运行时故障",
    },
    actions: {
      restart: "重启运行时",
    },
    error: {
      desktopCommandFailed: "桌面外壳未能完成该运行时操作。",
      sidecarUnavailable: "运行时进程不可用。",
      requestTimeout: "运行时未在超时时间内响应。",
      transportFailure: "与运行时的本地通道出现错误。",
      protocolIncompatible: "运行时协议版本与本应用不兼容。",
      invalidDesktopRequest: "界面生成的运行时请求不符合协议。",
      invalidRuntimeResult: "运行时返回的结果不符合协议。",
      previewUnavailable: "设备预览已失效，请刷新后重试。",
      captureUnavailable: "截图已失效，请重新截取后重试。",
      projectAssetUnavailable:
        "模板图像不可用，请确认素材仍在项目中并重新选择。",
    },
    nodeError: {
      variableUninitialized: "图像变量尚未赋值，无法读取。",
    },
    runState: {
      starting: "正在启动",
      running: "正在运行",
      cancelling: "正在取消",
      succeeded: "已成功",
      failed: "已失败",
      cancelled: "已取消",
    },
    logLevel: {
      debug: "调试",
      info: "信息",
      warning: "警告",
      error: "错误",
    },
    execution: {
      steps: "{{count}} 步",
      itemCount: "{{count}} 项",
      tokensCreated: "{{count}} 代币",
      cacheHits: "缓存命中 {{count}} 次",
      terminalError: "错误代码：{{code}}",
      executionHistoryLabel: "执行历史",
      logHistoryLabel: "日志历史",
      valueHistoryLabel: "变量历史",
      showEarlier: "显示更早的 {{count}} 条记录",
      newActivity: "有最新动态",
      currentStep: "当前步骤",
      unknownNode: "未知节点 ({{id}})",
      nodeUnavailable: "节点在当前图中已不存在，无法定位",
      truncated: "（已截断）",
      dimensions: "{{width}} × {{height}}",
      empty: {
        execution: "暂无执行记录",
        logs: "暂无日志",
        values: "暂无变量值",
      },
      kind: {
        null: "空值",
        bool: "布尔",
        number: "数字",
        string: "文本",
        point: "坐标点",
        rect: "矩形",
        image: "图像",
        ocrCandidate: "OCR 候选",
        ocrResult: "OCR 结果",
        collection: "集合",
      },
    },
    notices: {
      hostUnavailable: {
        title: "当前环境无法运行图",
        description:
          "运行时由桌面应用托管。在浏览器预览中打开时，界面可用但无法连接运行时。",
      },
      startFailed: {
        title: "运行时启动失败",
        description:
          "图执行需要运行时。可以重启运行时；若持续失败，请查看问题面板中的错误代码。",
      },
      incompatible: {
        title: "运行时版本不兼容",
        description:
          "运行时使用的协议版本与本应用不一致。重启无法解决，需要安装匹配的应用或运行时版本。",
      },
    },
    problems: {
      startFailed: {
        title: "运行时未能启动",
        description: "桌面外壳未能启动图运行时。图执行在恢复之前不可用。",
      },
      runRequestFailed: {
        title: "运行请求失败",
        description: "运行时未能开始或取消图执行。请查看错误代码后重试。",
      },
      runFailed: {
        title: "图执行失败",
        description:
          "节点或运行时操作失败，执行已停止。请查看执行面板和错误代码。",
      },
      registryLoadFailed: {
        title: "节点库加载失败",
        description:
          "运行时未能提供权威节点注册表。请重启运行时后再编辑或运行当前图。",
      },
      graphNotExecutable: {
        title: "当前图暂时无法运行",
        description:
          "运行时发现 {{count}} 条阻断或提示信息。请在问题面板中修复所有错误后重试。",
      },
      persistentVariableContextFailed: {
        title: "永久变量运行上下文失败",
        description:
          "无法安全关联本次运行的永久变量。运行结果不会写回永久变量。",
      },
      persistentVariableUpdateRejected: {
        title: "永久变量更新未保存",
        description: "运行时返回的永久变量不符合当前图定义，更新已被丢弃。",
      },
      persistentVariableStorageTemporary: {
        title: "永久变量仅在本次运行有效",
        description:
          "应用数据无法写入本机存储，本次运行期间仍会保留变量，但重启后不会保留。",
      },
    },
  },
  theme: {
    label: "界面主题",
    description: "默认跟随操作系统外观设置，也可以显式选择浅色或深色。",
    preferences: {
      system: "跟随系统",
      light: "浅色",
      dark: "深色",
    },
  },
  diagnostics: {
    severity: {
      error: "错误",
      warning: "警告",
      info: "信息",
    },
    actions: {
      dismiss: "忽略",
      dismissAll: "全部忽略",
      retry: "重试",
      reloadWindow: "重新加载窗口",
    },
    notifications: {
      regionLabel: "临时通知",
    },
    problems: {
      emptyTitle: "暂无问题",
      emptyDescription: "界面、运行时和项目出现需要处理的问题时会显示在这里。",
      applicationTitle: "应用与运行时问题",
      count: "{{count}} 个问题",
    },
    applicationError: {
      title: "Rino 遇到了问题",
      description:
        "程序遇到了无法恢复的界面错误。重新加载窗口可能丢失尚未保存的修改。",
      unknownMessage: "发生了未知错误。",
      details: "详细信息",
      copyDetails: "复制详细信息",
      detailsCopied: "详细信息已复制。",
      copyFailed: "无法访问剪贴板，请展开后手动复制。",
      errorType: "错误类型",
      errorMessage: "错误信息",
      stackTrace: "堆栈跟踪",
      componentStack: "组件堆栈",
    },
    featureError: {
      title: "{{feature}} 区域无法显示",
      description:
        "该区域遇到未预期的错误，应用的其余部分仍可继续使用。可以重试加载该区域。",
    },
  },
  locale: {
    languageLabel: "界面语言",
    description: "默认根据系统语言选择，也可以固定使用简体中文或英语。",
    preferences: {
      system: "跟随系统",
      zhCN: "简体中文",
      enUS: "英语（美国）",
    },
  },
} as const;

export type ZhCNTranslationCatalog = CatalogShape<typeof zhCNTranslation>;
